<?php
/*
    'taxi24.vn' => ['siteid' => 60, 'db_name' => 'DB_RM_HOST-6', 'layout_name' => 'taxi_v2' , 'use_own_meta_table'=>1,
        'use_snowflake_models' => 'FileUpload,MonitorItem,User,OrderItem,OrderInfo',
        'GOOGLE_CLIENT_ID'=>'985758689276-v0unqn5kfg2rdf9f8oag2arlh7nt0gt3.apps.googleusercontent.com',
        'force_fallback_language'=>'vi',
        'dbadmin' => "/phpmyadmin6868", 'enable_multi_language' =>1],

    ];



 */
return $GLOBALS['mMapDomainDb'] = [
    'mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021',
        'logo' => '/images/logo/mytree1.png',
        'rand_in_redis'=> 0,
        'use_snowflake_models' => 'FileUpload,GiaPha,MyTreeInfo,User,OrderItem,OrderInfo',
    ],
    'test1.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021',
        'logo' => '/images/logo/mytree1.png',
        'rand_in_redis'=> 1,
        'enable_multi_language' =>0
    ],
    'cdn-img-1.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-2.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-3.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-4.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-5.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-6.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-7.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-8.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'cdn-img-9.mytree.vn' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021', 'logo' => '/images/logo/mytree1.png'],
    'giapha.one' => ['siteid' => 1, 'db_name' => env('DB_DATABASE'), 'layout_name' => 'glx2021_gp_one', 'logo' => '/images/logo/mytree1.png'],
    'a101.galaxycloud.vn' => ['siteid' => 2, 'db_name' => 'glx01', 'layout_name' => 'a101'],
    'a102.galaxycloud.vn' => ['siteid' => 3, 'db_name' => 'glx102', 'layout_name' => ''],
    'a103.galaxycloud.vn' => ['siteid' => 4, 'db_name' => 'glx_dhshop', 'layout_name' => ''],
    "dh1.mytree.vn"   =>['siteid'=>5,'db_name'=>'glx_dhshop_test_demo', 'layout_name'=>''],
    //    "test.dhshop.shop"      =>['siteid'=>6,'db_name'=>'glx_dhshop_test_demo', 'layout_name'=>''],
//    "taxi.mytree.vn"      =>['siteid'=>6,'db_name'=>'glx_dhshop_test_demo', 'layout_name'=>''],
    'a104.galaxycloud.vn' => ['siteid' => 7, 'db_name' => 'glx04', 'layout_name' => ''],
    'a105.galaxycloud.vn' => ['siteid' => 8, 'db_name' => 'glx05', 'layout_name' => 'a105'],
    'test2023.galaxycloud.vn' => ['siteid' => 9, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'default'],
    'test2023.mytree.vn' => ['siteid' => 9, 'db_name' => 'glx2023_for_testing', 'layout_name' => ''],
    'hr.mytree.vn' => ['siteid' => 9, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'hr1'],
    'hosting.mytree.vn' => ['siteid' => 10, 'db_name' => 'glx10_sysdns', 'layout_name' => 'lte'],
    'user1.mytree.vn' => ['siteid' => 11, 'db_name' => 'glx10_user1', 'layout_name' => 'mytree1'],
    'shop1.mytree.vn' => ['siteid' => 12, 'db_name' => 'glx_shop1', 'layout_name' => 'shop1'],
    'giapha1.mytree.vn' => ['siteid' => 13, 'db_name' => 'glx_giapha1', 'layout_name' => 'gp1'],
    'demo5.mytree.vn' => ['siteid' => 14, 'db_name' => 'glx00_gp_tpl', 'layout_name' => 'gp1'],
    'demo6.mytree.vn' => ['siteid' => 15, 'db_name' => 'glx_giapha6', 'layout_name' => 'gp1'],
    'hophan.mytree.vn' => ['siteid' => 16, 'db_name' => 'glx_gp_ho_phan_manh', 'layout_name' => 'gp1'],
    'phantoc.mytree.vn' => ['siteid' => 17, 'db_name' => 'glx_gp_phan_thuy', 'layout_name' => 'gp1'],
    'nguyengia.mytree.vn' => ['siteid' => 18, 'db_name' => 'glx_gp_gia_nguyen', 'layout_name' => 'gp1'],
    'trieuphu24h-shb.mytree.vn' => ['siteid' => 19, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'shb'],
    'trieuphu24h.com' => ['siteid' => 19, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'shb'],
    'trangia.mytree.vn' => ['siteid' => 20, 'db_name' => 'glx_20', 'layout_name' => 'gp1'],
    'buihoangroa.mytree.vn' => ['siteid' => 21, 'db_name' => 'glx_21', 'layout_name' => 'gp1'],
    'nguyenvanmao.mytree.vn' => ['siteid' => 22, 'db_name' => 'glx_22', 'layout_name' => 'gp1'],
    'network-marketing.mytree.vn' => ['siteid' => 23, 'db_name' => 'glx_net_marketting', 'layout_name' => 'netmark'],
    'demo-anh-khiem.mytree.vn' => ['siteid' => 24, 'db_name' => 'glx_gp_akhiem', 'layout_name' => 'gp1'],
    'acl.mytree.vn' => ['siteid' => 25, 'db_name' => 'glx_acl', 'layout_name' => 'hr1'],
    'alc.mytree.vn' => ['siteid' => 25, 'db_name' => 'glx_acl', 'layout_name' => 'hr1'],

    'tapdanhmay.mytree.vn' => ['siteid' => 26, 'db_name' => 'glx_typing_train', 'layout_name' => 'tap-danh-may'],

    'dieuhoa2023.mytree.vn' => ['siteid' => 27, 'db_name' => 'glx_dieuhoa', 'layout_name' => 'd-hoa-2023'],
    'suadieuhoabacninh.vn' => ['siteid' => 27, 'db_name' => 'glx_dieuhoa', 'layout_name' => 'd-hoa-2023'],
//    'misu.mytree.vn' => ['siteid' => 28, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'misu2023'],
//    'tailieuchuan.mytree.vn' => ['siteid' => 28, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'misu2023'],
    'laptrinh.mytree.vn' => ['siteid' => 28, 'db_name' => 'glx_chuvanan', 'layout_name' => 'chuvanan'],
    'daiviet.mytree.vn' => ['siteid' => 29, 'db_name' => 'glx_dai_viet', 'layout_name' => 'misu2023'],
    'dth.mytree.vn' => ['siteid' => 30, 'db_name' => 'glx_dth', 'layout_name' => 'misu2023'],
    'hateco.mytree.vn' => ['siteid' => 31, 'db_name' => 'glx_hateco', 'layout_name' => 'hateco'],
    'image.mytree.vn' => ['siteid' => 32, 'db_name' => 'glx_image', 'layout_name' => 'default'],
    'kiemtra.mytree.vn' => ['siteid' => 33, 'db_name' => 'glx_kiemtra', 'layout_name' => 'kiemtra'],
    'tailieuchuan.net' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin', 'is_index_elastic_file' => 1,
    'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile'
    ],
    'tailieuchuan.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin1.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin2.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin3.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin4.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin5.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    'toantin6.mytree.vn' => ['siteid' => 34, 'db_name' => 'glx_toan_tin', 'layout_name' => 'toan_tin'],
    '1k.4share.vn' => ['siteid' => 35, 'db_name' => 'glx_1kdl', 'layout_name' => 'fullcr'],
    'a1.pm33.net' => ['siteid' => 35, 'db_name' => 'glx_1kdl', 'layout_name' => 'fullcr'],
//    'ncbd.mytree.vn' => ['siteid' => 36, 'db_name' => 'glx2023_for_testing', 'layout_name' => 'ncbd'],
    'ncbd.mytree.vn' => ['siteid' => 36, 'db_name' => 'glx_event', 'layout_name' => 'ncbd'],

    'events.nghiencuubiendong.vn' => ['siteid' => 36, 'db_name' => 'DB_RM_HOST-2', 'layout_name' => 'ncbd',
        'use_own_meta_table'=>1,
        'sidebar-collapse' =>1 , 'dbadmin' => "/phpmyadmin000"],
    'events.dav.edu.vn' => ['siteid' => 36, 'db_name' => 'DB_RM_HOST-2', 'layout_name' => 'ncbd',
        'use_own_meta_table'=>1,

        'sidebar-collapse' =>1 , 'dbadmin' => "/phpmyadmin000"],
    '10.0.0.18' => ['siteid' => 36, 'db_name' => 'glx_test1', 'db_host' => 'db_glx' ,  'layout_name' => 'ncbd',
        'use_own_meta_table'=>1,  'sidebar-collapse' =>1 , 'dbadmin' => "/phpmyadmin000"],

    '12.0.0.116' => ['siteid' => 36, 'db_name' => 'glx_test1', 'db_host' => 'db_glx' ,  'layout_name' => 'ncbd',
        'use_own_meta_table'=>1,  'sidebar-collapse' =>1 , 'dbadmin' => "/phpmyadmin000"],


    'v2.4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => 'sandbox', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile', '4s_link' =>1,
        'use_own_meta_table'=>1,'is_index_elastic_file' => 1,
        'upload_domain'=>'https://v2up.4share.vn',
        'dbadmin' => "http://12.0.0.116/dkjahskldfbasdhflasldfasdf/"],

    'webup.4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => 'sandbox', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile', '4s_link' =>1,
        'use_own_meta_table'=>1,'is_index_elastic_file' => 1,
        'upload_domain'=>'https://v2up.4share.vn',
        'dbadmin' => "http://12.0.0.116/dkjahskldfbasdhflasldfasdf/"],


    '4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => 'sandbox', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile', '4s_link' =>1,
        'use_own_meta_table'=>1,'is_index_elastic_file' => 1,
        'upload_domain'=>'https://v2up.4share.vn',
        'upload_tmp_folder_glx'=>'/var/ufile',
        'dbadmin' => "http://12.0.0.116/dkjahskldfbasdhflasldfasdf/"],
    'api.4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => 'sandbox', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile', '4s_link' =>1,'is_index_elastic_file' => 1,
        'use_own_meta_table'=>1,
        'upload_tmp_folder_glx'=>'/var/ufile',
        'upload_domain'=>'https://v2up.4share.vn',
        'dbadmin' => "http://12.0.0.116/dkjahskldfbasdhflasldfasdf/"],

    'v2up.4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => 'sandbox', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs,FolderFile', '4s_link' =>1,'is_index_elastic_file' => 1,
        'use_own_meta_table'=>1,
        'upload_domain'=>'https://v2up.4share.vn',
        'upload_tmp_folder_glx'=>'/var/ufile',
        'dbadmin' => "http://12.0.0.116/dkjahskldfbasdhflasldfasdf/"],
//    '4share.vn' => ['siteid' => 38, 'db_name' => 'DB_RM_HOST-1', 'layout_name' => '4sv2', 'password_type' => 2,
//        'encode_id_rand_models' => 'FileUpload,DownloadLogs', '4s_link' =>1],
    'honguyencanh.chilaitrieutu.vn' => ['siteid' => 39, 'db_name' => 'glx_giapha1', 'layout_name' => 'gp2'],
    'ncbd2.mytree.vn' => ['siteid' => 40, 'db_name' => 'DB_RM_HOST-2', 'layout_name' => 'ncbd'],
    'cloud1.mytree.vn' => ['siteid' => 41, 'db_name' => 'glx_cloud1', 'layout_name' => 'cloud1', 'password_type' => 2,],
    'zcloud.io.vn' => ['siteid' => 41, 'db_name' => 'glx_cloud1', 'layout_name' => 'cloud1', 'password_type' => 2,
        'enable_doc_edit'=>1,
        ],

    'vientim.mytree.vn' => ['siteid' => 42, 'db_name' => 'glx_vientim', 'layout_name' => 'vtim', 'password_type' => 2,
        'encode_id_rand_models' => 'FileUpload,DownloadLogs',
        'enable_doc_edit'=>1,
        'use_own_meta_table'=>1,
    ],
    'draw.mytree.vn' => ['siteid' => 42, 'db_name' => 'glx_vientim', 'layout_name' => 'vtim', 'password_type' => 2,
        ],
    'dinhnb.mytree.vn' => ['siteid' => 43, 'db_name' => 'glx_dinhnb', 'layout_name' => 'gp2'],
    'dna1.mytree.vn' => ['siteid' => 44, 'db_name' => 'glx_dna1', 'layout_name' => 'dna1',],
    'trolyao.com.vn' => ['siteid' => 44, 'db_name' => 'glx_dna1', 'layout_name' => 'dna1',],
    'ai.mytree.vn' => ['siteid' => 45, 'db_name' => 'glx_ai1', 'layout_name' => 'ai3g',],
    'datapro.mytree.vn' => ['siteid' => 46, 'db_name' => 'glx_datapro', 'layout_name' => 'datapro',],
    'tkweb.mytree.vn' => ['siteid' => 47, 'db_name' => 'glx_thietkeweb', 'layout_name' => 'thietkeweb',],
    'task.mytree.vn' => ['siteid' => 48, 'db_name' => 'glx_task_mng', 'layout_name' => 'taskmng',],
    'quantri.hzmplastic.com.vn' => ['siteid' => 49, 'db_name' => 'glx_hzm', 'layout_name' => 'hzm',],
    'movie1.mytree.vn' => ['siteid' => 50, 'db_name' => 'glx_movie1', 'layout_name' => 'movie1',],
    'support.galaxycloud.vn' => ['siteid' => 51, 'db_name' => 'glx_movie1', 'layout_name' => 'supportglx',],
    'zalo.galaxycloud.vn' => ['siteid' => 51, 'db_name' => 'glx_movie1', 'layout_name' => 'supportglx',],
    'khoinghiep.mytree.vn' => ['siteid' => 52, 'db_name' => 'glx_startup', 'layout_name' => 'sandbox-startup',],
    'startup.mytree.vn' => ['siteid' => 52, 'db_name' => 'glx_startup', 'layout_name' => 'sandbox-startup',],
    'taxi.mytree.vn' => ['siteid' => 53, 'db_name' => 'glx_taxi1', 'layout_name' => 'taxi1',],
    'aitaxinoibai.vn' => ['siteid' => 53, 'db_name' => 'glx_taxi1', 'layout_name' => 'taxi1',],
    'camera.mytree.vn' => ['siteid' => 54, 'db_name' => 'glx_camera', 'layout_name' => 'camera1',],
    'v3.mytree.vn' => ['siteid' => 55, 'db_name' => 'DB_PG1...', 'layout_name' => 'glx2021', 'use_own_meta_table'=>1,
        'use_snowflake_models' => 'FileUpload,GiaPha,MyTreeInfo',],
    'v5.mytree.vn' => ['siteid' => 56, 'db_name' => 'glx_2025_mytree', 'layout_name' => 'glx2021', 'use_own_meta_table'=>1,
         'use_snowflake_models' => 'FileUpload,GiaPha,MyTreeInfo,User,OrderItem,OrderInfo',],
    'monitor.mytree.vn' => ['siteid' => 57, 'db_name' => 'glx_monitor_v2', 'layout_name' => 'monitor_v2',
        'use_snowflake_models' => 'MonitorItem,MonitorConfig,MonitorSetting,User,OrderItem,OrderInfo'
        ],
    'monitor-test.mytree.vn' => ['siteid' => 58, 'db_name' => 'DB_RM_HOST-3', 'layout_name' => 'monitor_v2',],
//    'mon.lad.vn' => ['siteid' => 59, 'db_name' => 'DB_PG2...', 'layout_name' => 'monitor_v2', 'use_own_meta_table'=>1]
    'mon.lad.vn' => ['siteid' => 59, 'db_name' => 'DB_RM_HOST-5', 'layout_name' => 'monitor_v2' , 'use_own_meta_table'=>1,
        'dbadmin' => "/phpmyadmin6868", 'enable_multi_language' =>1],

    'ping24.io' => ['siteid' => 59, 'db_name' => 'DB_PG2',
        'GOOGLE_CLIENT_ID'=>'916524608033-lhqrsnqrr4c608cab9b14a13n40qa2pn.apps.googleusercontent.com',
//        'ping365.io' => ['siteid' => 59, 'db_name' => 'DB_RM_HOST-5',
        'layout_name' => 'monitor_v2' ,
        'use_own_meta_table'=>1,
        'use_snowflake_models' => 'FileUpload,MonitorItem,User,OrderItem,OrderInfo',
        'force_fallback_language'=>'en',
    'dbadmin' => "/phpmyadmin6868", 'enable_multi_language' =>1],

//   'mon.lad.vn' => ['siteid' => 59, 'db_name' => 'DB_PG2...', 'layout_name' => 'monitor_v2', 'use_own_meta_table'=>1]
    'taxi.lad.vn' => ['siteid' => 60, 'db_name' => 'DB_RM_HOST-6', 'layout_name' => 'taxi_v2' , 'use_own_meta_table'=>1,
        'use_snowflake_models' => 'FileUpload,MonitorItem,User,OrderItem,OrderInfo',
        'GOOGLE_CLIENT_ID'=>'985758689276-v0unqn5kfg2rdf9f8oag2arlh7nt0gt3.apps.googleusercontent.com',
    'dbadmin' => "/phpmyadmin6868", 'enable_multi_language' =>1],

    'taxi24.vn' => ['siteid' => 60, 'db_name' => 'DB_RM_HOST-6', 'layout_name' => 'taxi_v2' , 'use_own_meta_table'=>1,
        'use_snowflake_models' => 'FileUpload,MonitorItem,User,OrderItem,OrderInfo',
        'GOOGLE_CLIENT_ID'=>'985758689276-v0unqn5kfg2rdf9f8oag2arlh7nt0gt3.apps.googleusercontent.com',
        'force_fallback_language'=>'vi',
        'dbadmin' => "/phpmyadmin6868", 'enable_multi_language' =>1],

    'thansohoc.lad.vn' => ['siteid' => 61, 'db_name' => 'DB_RM_HOST-7', 'layout_name' => 'thansohoc',
        'use_own_meta_table'=>1,
        'force_fallback_language'=>'vi',
        'enable_multi_language' =>1],

    'lad.vn' => ['siteid' => 62, 'db_name' => 'DB_RM_HOST-7', 'layout_name' => 'ladvn',
        'use_own_meta_table'=>1,
        'force_fallback_language'=>'vi',
        'enable_multi_language' =>1],
    'glx.lad.vn' => ['siteid' => 63, 'db_name' => 'DB_RM_HOST-8', 'layout_name' => 'glxv3',
        'use_own_meta_table'=>1,
        'force_fallback_language'=>'vi',
        'dbadmin' => "/phpmyadmin6868",
        'enable_multi_language' =>1],

    'localhost' => ['siteid' => 64, 'db_name' => 'glx2026', 'layout_name' => 'glxv3',
        'use_own_meta_table'=>1,
//        'force_fallback_language'=>'vi',
        'dbadmin' => "/phpmyadmin6868",
//        'enable_multi_language' =>1
    ],
    ];



