<?php

namespace App\Http\ControllerApi;

use App\Components\clsParamRequestEx;
use App\Models\HrMessageTask;
use App\Models\HrMessageTask_Meta;
use App\Models\HrTask;
use App\Repositories\HrTaskRepositoryInterface;
use Illuminate\Http\Request;

class HrTaskControllerApi extends BaseApiController
{
    public function __construct(HrTaskRepositoryInterface $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function update($id, Request $request)
    {

        $found = 0;

        if ($obj = HrTask::find($id)) {
            $found = 1;
            $oldDone = $obj->done;
        }

        $ret = parent::update($id, $request); // TODO: Change the autogenerated stub

        if ($found) {
            if ($obj = HrTask::find($id)) {
                if ($oldDone != $obj->done) {
                    $taskMess = new HrMessageTask();
                    $uid = $taskMess->user_id = getUserIdCurrentInCookie();
                    $taskMess->task_id = $id;
                    if ($obj->done) {
                        $taskMess->message = '[Đánh dấu Hoàn Thành]';
                    } else {
                        $taskMess->message = '[Đánh dấu Chưa Hoàn Thành]';
                    }
                    $taskMess->save();

                    HrMessageTask_Meta::pushMessageOfTaskHr($id, $uid, $taskMess);

                }
            }
        }

        return $ret;
    }
}
