<?php

namespace App\Http\ControllerApi;

use App\Components\clsParamRequestEx;
use App\Components\Helper1;
use App\Helpers\TelegramHelper;
use App\Models\MonitorConfig;
use App\Models\MonitorItem;
use App\Models\MonitorUser;
use App\Repositories\MonitorItemRepositoryInterface;
use Illuminate\Http\Request;

class MonitorItemControllerApi extends BaseApiController
{
    public function __construct(MonitorItemRepositoryInterface $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function add(Request $request)
    {
//        MonitorItem::checkQuota($uid, "Add new monitor item");
        $ret  = $this->validateInsertUpdate($id = null, $request);
        if($ret)
            return $ret;
        return parent::add($request); // TODO: Change the autogenerated stub
    }

    function validateInsertUpdate($id = null, Request &$request)
    {

//        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//        print_r($request->all());
//        echo "</pre>";
        $mon = null;
        if($id)
        if(Helper1::isAdminModuleApi($request))
            return parent::update($id, $request); // TODO: Change the autogenerated stub

        $objUser = getCurrentUserId(1);
        $uid = $objUser->getId();
        if($id){
            $mon = MonitorItem::find($id);
            if (!$mon) {
                return rtJsonApiError(__('monitor.api.not_found'));
            }


            if ($mon->user_id != getCurrentUserId()) {
                return rtJsonApiError(__('monitor.api.no_permission_edit'));
            }
        }
        $domain = getDomainHostName();
        $nAllow = MonitorUser::getCurrentNumberMonitorAllow($uid);
        $nEnable = MonitorItem::countEnableByUser($uid);

        $meta = MonitorItem::getMetaObj();

        $desc1 = $meta->getDescOfField('check_interval_seconds', 0, $objUser->language ?? '');
        $desc2 = $meta->getDescOfField('allow_alert_for_consecutive_error', 0, $objUser->language ?? '');

//        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//        print_r($mm);
//        echo "</pre>";


        if ($nEnable >= $nAllow)
            if (!$mon || !$mon->enable)
                if ($request->enable) {
                    return response()->json(['code' => -1, 'payload' => __('monitor.api.exceeded_limit'),
                        'message' => __('monitor.api.exceeded_limit'), 'error_link' => "https://$domain/pricing"], 400);

//            return rtJsonApiError(__('monitor.api.exceeded_limit'));
                }

        if ($nAllow <= DEF_MONITOR_DEFAULT_FREE_QUOTA)
        {
            if($request->check_interval_seconds)
                if ($request->check_interval_seconds <= 60) {

                    return response()->json(['code' => -1, 'payload' => __('monitor.api.interval_too_short_for_free'),
                        'message' => __('monitor.api.interval_too_short_for_free', ['desc' => $desc1]), 'error_link' =>
                            ['link'=>"https://$domain/pricing", 'text' => __('monitor.api.upgrade_here')]
                    ], 400);

                }
            if ($request->allow_alert_for_consecutive_error) {
                return response()->json(['code' => -1, 'payload' => __('monitor.api.allow_alert_for_consecutive_error_for_free'),
                    'message' => __('monitor.api.allow_alert_for_consecutive_error_for_free', ['desc' => $desc2]), 'error_link' => "https://$domain/pricing"], 400);
            }
        }


        $attachedAlerts = [];
        if(is_array($request->_mount_alert_id)){

            foreach ($request->_mount_alert_id as $alertId){
                if($mon ?? '')
                if($mon = MonitorConfig::find($alertId)){
                    if($mon->user_id != $uid)
                        return rtJsonApiError(__('monitor.api.no_permission_alert', ['alert_id' => "$alertId | $mon->user_id != $uid"]));
                    $attachedAlerts[] = $alertId;
                }
            }

            //$request->_mount_alert_id là mảng các id của MonitorConfig
            // và có bảng MonitorItems, rồi bảng pivot: monitor_and_configs
            # $id ở đây là của MonitorItem đang update
            //Vậy sync thế nào đó để vào bảng monitor_and_configs

            if($id)
            MonitorItem::find($id)->syncAlertConfigs($attachedAlerts);

            // _mount_alert_id bỏ ra khỏi request
            $request->merge(['_mount_alert_id' => null]);

        }

        // echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
        // print_r($attachedAlerts);
        // echo "</pre>";
        // die();



        $url = $request->url_check = trim($request->url_check);
        if($url)
            $request->merge(['url_check' => $request->url_check]);

        if($request->type == 'open_port_tcp_then_error' || $request->type == 'open_port_udp_then_error'){

            if(!str_contains($url, ':')){
                return rtJsonApiError(__("monitor.api.invalid_format_port"));
            }
            $parts = explode(':', $url);
            if(count($parts) != 2){
                return rtJsonApiError(__("monitor.api.invalid_format_port"));
            }

            $port = $parts[1] ?? '';
            $domain = $parts[0] ?? '';

            //Kiem tra valide domain and port:
            if(!is_numeric($port) || $port < 1 || $port > 65535){
                return rtJsonApiError(__('monitor.api.invalid_port_number'));
            }
            if(!filter_var($domain, FILTER_VALIDATE_DOMAIN, FILTER_NULL_ON_FAILURE) && !filter_var($domain, FILTER_VALIDATE_IP, FILTER_NULL_ON_FAILURE)){
                return rtJsonApiError(__('monitor.api.invalid_domain_ip'));
            }
        }
    }

    public function update($id, Request $request)
    {

        $ret  = $this->validateInsertUpdate($id, $request);
        if($ret)
            return $ret;
//        die();
        return parent::update($id, $request); // TODO: Change the autogenerated stub
    }

    function update_alert()
    {

        try {

//        die("111");
        $obj = new MonitorItem();

        //Lấy các tham số này ra
        //config_id=${alertId}&monitor_item_id=${objDataId}&action=${isChecked ? 'add' : 'remove'
        $alertId = request('config_id');
        $itemId = request('monitor_item_id');
        $action = request('action');

        //Bảng monitor_and_configs là pivot table giữa monitor_items và monitor_configs
        //Cột monitor_item_id, config_id

        if ($action == 'add') {
            // Thêm bản ghi vào bảng monitor_and_configs
            $obj->attachAlertToItem($itemId, $alertId);
        } else {
            // Xóa bản ghi khỏi bảng monitor_and_configs
            $obj->detachAlertFromItem($itemId, $alertId);
        }

        }
        catch (\Exception $e) {
            return rtJsonApiError(__('monitor.api.update_error', ['message' => $e->getMessage()]));
        }
        return rtJsonApiDone(__('monitor.api.update_success'), __('monitor.api.update_success'));
    }
}
