<?php

namespace App\Http\ControllerApi;

use App\Components\clsParamRequestEx;
use App\Components\Helper1;
use App\Models\OrderInfo;
use App\Models\OrderShip;
use App\Models\Telesale;
use App\Repositories\TelesaleRepositoryInterface;
use Illuminate\Http\Request;
use Shopee\Nodes\Order\Order;

class TelesaleControllerApi extends BaseApiController
{
    public function __construct(TelesaleRepositoryInterface $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function add(Request $request)
    {
        return rtJsonApiError('Không cần add telesale!');
    }

    public function update($id, Request $request)
    {
        if ($id < 0) {
            return rtJsonApiError('Không cần thêm telesale, vì telesale được import tự động từ Đơn hàng!');
        }

        $rq = $request->toArray();
        //Request chỉ được đổi thông tin về Log , comment
        //if(isSupperAdmin_())
        if (Helper1::isMemberModule()) {
            //            echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
            //            print_r($rq);
            //            echo "</pre>";
            //            die("ABC = ");
            if ($request->order_status) {
                if ($od = OrderInfo::find($id)) {
                    if ($od->order_status != $request->order_status) {
                        $od->order_status = $request->order_status;
                        $od->updateAndTag('update order_status because telesale update');
                    }
                }
            }

            if ($tl = Telesale::find($id)) {
                if ($tl instanceof Telesale);
                //    if(OrderShip::where(['order_id'=>$tl->id])->whereNotNull('remote_tracking_id')->where('remote_tracking_id', '>', '0')->first())
                if ($od = OrderShip::where('order_id', $id)->first()) {

                    if ($tl->khongChoCapNhatTeleObj()) {
                        foreach ($rq as $key => $val) {
                            if ($key != 'note2') {
                                if ($val != $tl->$key) {
                                    return rtJsonApiError('Đơn đã gửi sang Ship, chỉ có thể thay đổi Ghi Chú');
                                }
                                //unset($request[$key]);
                            }
                        }
                    }
                }
            }

        }

        return parent::update($id, $request); // TODO: Change the autogenerated stub
    }
}
