<?php

namespace App\Http\ControllerApi;

use App\Components\clsParamRequestEx;
use App\Components\Helper1;
use App\Models\User;
use App\Models\VpsInstance;
use App\Models\VpsUsage;
use App\Repositories\VpsInstanceRepositoryInterface;
use Google\Service\Compute\Help;
use Illuminate\Http\Request;

class VpsInstanceControllerApi extends BaseApiController
{
    public function __construct(VpsInstanceRepositoryInterface $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
        //Nếu =0, là ko set quyen UID nao ca
//        $objPrEx->need_set_uid = 0;
        parent::__construct();
    }

//    public function update($id, Request $request)
//    {
//        if(Helper1::isAdminModuleApi($request)){
//
//            if(isAdminLrv_())
//            if($request->user_id && is_numeric($request->user_id)){
//                if(User::find($request->user_id))
//                    if(VpsInstance::find($id))
//                        if($vpsUsage = VpsUsage::where("instance_id", $id)->first()){
//                            $old = $vpsUsage->user_id;
//                            if($vpsUsage->user_id != $request->user_id){
//                                $vpsUsage->user_id = $request->user_id;
//                                $vpsUsage->addLog("Update uid : $old -> $request->user_id");
//                                $vpsUsage->update();
//                            }
//                        }
//            }
//        }
//
//        return parent::update($id, $request); // TODO: Change the autogenerated stub
//    }
}
