<div class="elementor-element elementor-element-195b316 e-flex e-con-boxed e-con e-child" data-id="195b316" data-element_type="container" data-e-type="container"><div class="e-con-inner"><div class="elementor-element elementor-element-b0c97b1 e-con-full e-flex e-con e-child" data-id="b0c97b1" data-element_type="container" data-e-type="container"><div class="elementor-element elementor-element-75fee3b elementor-widget elementor-widget-pricing_box" data-id="75fee3b" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-2 x P40</div><div class="desc">Máy chủ riêng với 2 card  Nvidia Tesla P40</div></div><div class="price_wrap"><div class="price">
<strong>9.000.000 </strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="https://panel.thuegpu.vn/store/gpu-server">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon 2667v4</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU 2 x Nvidia Tesla P40 24G</li><li>CUDA Core 2 x 3840</li><li>01 IP V4</li><li>24/7 Support</li></ul></div></div></div></div><div class="elementor-element elementor-element-7cf167e elementor-widget elementor-widget-pricing_box" data-id="7cf167e" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-8x3090</div><div class="desc">Máy chủ riêng với 8 card  Nvidia RTX3090</div></div><div class="price_wrap"><div class="price">
<strong>60.000.000 </strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 8 x Nvidia RTX 3090 24GB</li><li>CUDA Core 8 x 10496</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-c388044 elementor-widget elementor-widget-pricing_box" data-id="c388044" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-4 x A30</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>80.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 2 X Nvidia A30 24GB</li><li>Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-f2ca7dd elementor-widget elementor-widget-pricing_box" data-id="f2ca7dd" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-RTX 4090</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>20.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia RTX 4090 24GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-871e6e6 elementor-widget elementor-widget-pricing_box" data-id="871e6e6" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU- L40S</div><div class="desc">Máy chủ thế hệ mới với GPU L40S</div></div><div class="price_wrap"><div class="price">
<strong>37.500.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia L40S 48GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-299f2c6 elementor-widget elementor-widget-pricing_box" data-id="299f2c6" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-A100 40G</div><div class="desc">Máy chủ thế hệ mới với GPU A100 40GB</div></div><div class="price_wrap"><div class="price">
<strong>40.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia A100 40GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div></div><div class="elementor-element elementor-element-c1f96e0 e-con-full e-flex e-con e-child" data-id="c1f96e0" data-element_type="container" data-e-type="container"><div class="elementor-element elementor-element-480fb3f elementor-widget elementor-widget-pricing_box" data-id="480fb3f" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box is_popular"><div class="box_info"><div class="heading_wrap"><div class="title">GPU-2 x 3090</div><div class="desc">Máy chủ riêng với 2 card Nvidia RTX 3090</div></div><div class="price_wrap"><div class="price">
<strong>20.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="https://panel.thuegpu.vn/store/gpu-server">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li>CPU 2 x Intel Xeon 2667v4</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU 2 x Nvidia RTX 3090 24G</li><li>CUDA Core 2 x 10496</li><li>01 IP V4</li><li>24/7 Support</li></ul></div></div></div></div><div class="elementor-element elementor-element-b8f3223 elementor-widget elementor-widget-pricing_box" data-id="b8f3223" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-A30</div><div class="desc">Máy chủ riêng với 1 card  Nvidia A30</div></div><div class="price_wrap"><div class="price">
<strong>25.000.000 </strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia A30 24GB</li><li>Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-66ceb7e elementor-widget elementor-widget-pricing_box" data-id="66ceb7e" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-4 x V100</div><div class="desc">Máy chủ GPU SXM2 - Hỗ trợ Nvlink</div></div><div class="price_wrap"><div class="price">
<strong>50.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 4 X Nvidia Tesla V100 32GB</li><li>SXM2 Nvlink AI Server</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-315d7da elementor-widget elementor-widget-pricing_box" data-id="315d7da" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-2 x 4090</div><div class="desc">Máy chủ AI mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>35.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 2 x Nvidia RTX 4090</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-6b54f2a elementor-widget elementor-widget-pricing_box" data-id="6b54f2a" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-RTX 5880</div><div class="desc">Máy chủ AI mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>35.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia RTX 5880 ADA 48GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-1fe73d6 elementor-widget elementor-widget-pricing_box" data-id="1fe73d6" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-A100 80G</div><div class="desc">Máy chủ thế hệ mới với GPU A100 80GB</div></div><div class="price_wrap"><div class="price">
<strong>80.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia A100 80GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div></div><div class="elementor-element elementor-element-09f6990 e-con-full e-flex e-con e-child" data-id="09f6990" data-element_type="container" data-e-type="container"><div class="elementor-element elementor-element-3e813cf elementor-widget elementor-widget-pricing_box" data-id="3e813cf" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-4 x 3090</div><div class="desc">Tận hưởng việc tối ưu hóa hiệu suất &amp; tài nguyên riêng</div></div><div class="price_wrap"><div class="price">
<strong>35.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="https://panel.thuegpu.vn/store/gpu-server">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li>CPU 2 x Intel Xeon 2667v4</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU 4 x Nvidia RTX 3090 24G</li><li>CUDA Core 4 x 10496</li><li>01 IP V4</li><li>24/7 Support</li></ul></div></div></div></div><div class="elementor-element elementor-element-8e2f219 elementor-widget elementor-widget-pricing_box" data-id="8e2f219" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-2xA30</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>45.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 2 X Nvidia A30 24GB</li><li>Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-108cca2 elementor-widget elementor-widget-pricing_box" data-id="108cca2" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-A40</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>35.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia A40 48GB</li><li>Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-9f6dae0 elementor-widget elementor-widget-pricing_box" data-id="9f6dae0" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-4 x 4090</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>65.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>256 GB Ram</li><li>4TB SSD NVME</li><li>GPU 4 x Nvidia RTX 4090</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-b69e99f elementor-widget elementor-widget-pricing_box" data-id="b69e99f" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-RTX 6000</div><div class="desc">Máy chủ Tensor Core mạnh mẽ thế hệ mới</div></div><div class="price_wrap"><div class="price">
<strong>37.500.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia RTX 6000 ADA 48GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div><div class="elementor-element elementor-element-9be5d8e elementor-widget elementor-widget-pricing_box" data-id="9be5d8e" data-element_type="widget" data-e-type="widget" data-widget_type="pricing_box.default"><div class="elementor-widget-container"><div class="pricing_box "><div class="box_info"><div class="heading_wrap"><div class="title">GPU-H100 80G</div><div class="desc">Máy chủ thế hệ mới với GPU H100 80GB</div></div><div class="price_wrap"><div class="price">
<strong>95.000.000</strong>
<span>VND/tháng</span></div><div class="promo">- 15% khi thanh toán 12 tháng</div></div><div class="actions_wrap">
<a target="_blank" rel="nofollow" href="#">Đăng ký gói</a></div></div><div class="box_checklist"><ul><li> CPU 2 x Intel Xeon Gold 6133</li><li>128 GB Ram</li><li>2TB SSD NVME</li><li>GPU Nvidia H100 80GB</li><li>Cuda Core - Tensor Core GPU</li><li>01 IP V4</li><li>Liên hệ  Support để đặt hàng</li></ul></div></div></div></div></div></div></div>