<?php

namespace App\Http\Controllers;

use App\Components\clsParamRequestEx;
use App\Models\DownloadLog;

class DownloadLogController extends BaseController
{
    protected DownloadLog $data;

    public function __construct(DownloadLog $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function index()
    {

        return parent::index(); // TODO: Change the autogenerated stub
    }

//    public function edit($id)
//    {
//        $this->objParamEx->set_field_uid = 'user_id_file';
//        return parent::edit($id); // TODO: Change the autogenerated stub
//    }

    public function index_user_download_your_file()
    {
        $this->objParamEx->set_field_uid = 'user_id_file';
        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function tree_index()
    {
        $objMeta = $this->data::getMetaObj();
        return view('admin.default-tree', compact('objMeta'));
    }
}
