<?php

namespace App\Http\Controllers;

use App\Components\clsParamRequestEx;
use App\Components\Helper1;
use App\Models\OrderInfo;
use App\Models\Telesale;
use App\Models\User;

class TelesaleController extends BaseController
{
    protected Telesale $data;

    public function __construct(Telesale $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function index()
    {
        //Nếu là member, thì sẽ
        if (Helper1::isMemberModule()) {

            $uid = getUserIdCurrentInCookie();
            if (! $uid) {
                loi('Lỗi Không có UID session cookie?');
            }
            $mm = OrderInfo::where('order_status', '!=', 1)->limit(30)->get()->toArray();
            //            dump($mm);
            $cc = 0;
            foreach ($mm as $obj) {
                //            echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
                //            print_r($obj);
                //            echo "</pre>";
                if (! $obj['order_status']) {
                    $obj['order_status'] = 0;
                }
                $obj['user_id'] = $uid;
                $obj['order_id_link'] = $obj['id'];

                if (! $obj['phone_request'] || strlen($obj['phone_request']) < 6) {
                    continue;
                }
                if (! $obj['to_address'] || strlen($obj['phone_request']) < 6) {
                    continue;
                }

                if (! Telesale::find($obj['id']) && ! Telesale::withTrashed()->find($obj['id'])) {
                    Telesale::create($obj);
                    if ($cc > 5) {
                        break;
                    }
                }
            }

            //Tìm các đơn của user sai trạng thái, fix lại
            //Telesale::where(['user_id'=>$uid ])->where('order_status', '!=', DEF_SHOP_STATUS_TELE_KHACH_CHOT_DON);

        }
        //        die();

        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function tree_index()
    {
        $objMeta = $this->data::getMetaObj();

        return view('admin.default-tree', compact('objMeta'));
    }
}
