<?php

namespace App\Http\Controllers;

use App\Components\clsParamRequestEx;
use App\Models\TmpDownloadSession;

class TmpDownloadSessionController extends BaseController
{
    protected TmpDownloadSession $data;

    public function __construct(TmpDownloadSession $data, clsParamRequestEx $objPrEx)
    {
        $this->data = $data;
        $this->objParamEx = $objPrEx;
    }

    public function index_user_download_your_file()
    {
        $this->objParamEx->set_field_uid = 'user_id_file';
        return parent::index(); // TODO: Change the autogenerated stub
    }


    public function tree_index()
    {
        $objMeta = $this->data::getMetaObj();

        return view('admin.default-tree', compact('objMeta'));
    }
}
