<?php

namespace App\Models;

use App\Components\Helper1;
use Elasticsearch\Endpoints\Cat\Help;
use LadLib\Common\Database\MetaOfTableInDb;
use LadLib\Common\UrlHelper1;

/**
 * ABC123
 *
 * @param null $objData
 */
class EventInfo_Meta extends MetaOfTableInDb
{
    protected static $api_url_admin = '/api/event-info';

    protected static $web_url_admin = '/admin/event-info';

    protected static $api_url_member = '/api/member-event-info';

    protected static $web_url_member = '/member/event-info';

    //    static $eventChanel = 'event-mng-channel';
    public static $eventChanel = 'event001';

    public static $titleMeta = 'Danh mục Sự kiện';

    public static $folderParentClass = EventInfo::class;
    public static $modelClass = EventInfo::class;

    public static $allowAdminShowTree = 1;

    public static $typeEmail = 'email';

    public static $typeSms = 'sms';

    /**
     * @return string
     */
    public static function getApiUrlMember(): string
    {
        return self::$api_url_member;
    }


    public static function getDefaultTemplateId()
    {
        return 6; // TODO: Change the autogenerated stub
    }

    public static function getDefaultTemplateField()
    {
        return [
            'sms_content1',
            'sms_content2',
            'sms_content3',
            'sms_content1_en',
            'sms_content2_en',
            'sms_content3_en',

            'content1',
            'content2',
            'content3',
            'content1_en',
            'content2_en',
            'content3_en',

            'mail_title1',
            'mail_title1_en',
            'mail_title2',
            'mail_title2_en',
            'mail_title3',
            'mail_title3_en',

            'reg_mail_title_vi1',
            'reg_mail_title_vi2',
            'reg_mail_title_en1',
            'reg_mail_title_en2',

            'reg_mail_01_vi',
            'reg_mail_02_vi',
            'reg_mail_01_en',
            'reg_mail_02_en',

            'reg_text_vn',
            'reg_text_en',
            'reg_text_ok_vn',
            'reg_text_ok_en',
            ];
    }


    /**
     * @return MetaOfTableInDb
     */
    public function getHardCodeMetaObj($field)
    {
        $objSetDefault = new MetaOfTableInDb();
        $objMeta = new MetaOfTableInDb();

        $objSetDefault->setDefaultMetaTypeField($field);
        $objMeta->dataType = $objSetDefault->dataType;

        if ($field == 'status' || $field == 'require_sign'
            || $field == 'require_sign_this_event'
            || $field == 'user_need_image_to_reg'
            || $field == 'enable_reg_bank'
        ) {
            $objMeta->dataType = DEF_DATA_TYPE_STATUS;
        }
        if ($field == 'time_start' || $field == 'time_end') {
            $objMeta->dataType = DEF_DATA_TYPE_IS_DATE_TIME;
        }

        if ($field == 'content3' || $field == 'content1' || $field == 'content2' ||
            $field == 'content3_en' || $field == 'content1_en' || $field == 'content2_en'
        ) {
            $objMeta->dataType = DEF_DATA_TYPE_RICH_TEXT;
        }
        if ($field == 'department') {
            $objMeta->dataType = DEF_DATA_TYPE_HTML_SELECT_OPTION;

        }
        if (str_starts_with($field, 'sms_content')) {
            $objMeta->dataType = DEF_DATA_TYPE_TEXT_AREA;
        }

        if (str_starts_with($field, 'reg_text_')) {
            $objMeta->dataType = DEF_DATA_TYPE_TEXT_AREA;
        }

        if(in_array($field, ['web_text_confirm_join_event_vi', 'web_text_confirm_join_event_en'])){
            $objMeta->dataType = DEF_DATA_TYPE_RICH_TEXT;
        }

        if (str_starts_with($field, 'reg_mail_0')) {
            $objMeta->dataType = DEF_DATA_TYPE_TEXT_AREA;
        }

        if($field == 'allow_public_reg'){
            $objMeta->dataType = DEF_DATA_TYPE_STATUS;
        }

        if (
            $field == 'attached_files_email1' ||
            $field == 'attached_files_email1_en' ||
            $field == 'attached_files_email2' ||
            $field == 'attached_files_email2_en' ||
            $field == 'attached_files_email3' ||
            $field == 'attached_files_email3_en' ||
            $field == 'files') {
            $objMeta->dataType = DEF_DATA_TYPE_IS_MULTI_IMAGE_BROWSE;
        }

        if ($field == 'image_list') {
            $objMeta->dataType = DEF_DATA_TYPE_IS_MULTI_IMAGE_BROWSE;
        }

        if ($field == 'image_register') {
            $objMeta->dataType = DEF_DATA_TYPE_IS_ONE_IMAGE_BROWSE;
        }

        if ($field == 'tag_list_id') {
            $objMeta->join_api_field = 'name';
            //          $objMeta->join_func = 'joinTags';
            //EventInfo edit, tag sẽ ko update được?
            $objMeta->join_relation_func = 'joinTags';
            $objMeta->join_api = '/api/tags/search';
            $objMeta->dataType = DEF_DATA_TYPE_ARRAY_NUMBER;
        }

        if ($field == 'parent_id' || $field == 'parent2') {
            $objMeta->dataType = DEF_DATA_TYPE_TREE_SELECT;
            $objMeta->join_api = '/api/event-info';
            $objMeta->join_api = '/api/member-event-info';
        }

        return $objMeta;
    }

    function getExtraDataEditFieldNameX1($field)
    {
        $mm = ['content', 'content1', 'content2', 'content3' ,'content_en', 'content1_en', 'content2_en', 'content3_en'  ];
        if(in_array($field, $mm)){
?>
            <button type='button' class='btn btn-sm btn-default my-2' onclick='previewField("<?php echo $field ?>")' title="Xem trước Nội dung trước khi gửi - khi bỏ các dòng có ### ở đầu, Nếu chưa bỏ dòng, hãy copy nội dung ra Notepad rồi copy paste lại vào đây, edit lại nội dung!
Nguyên nhân là do edit dạng web phức tạp, nhiều mẫu không nhận ra được khi thay đổi nhiều
">
                Xem trước
            </button>

            <?php
        }
    }

    public static function getEventChanelName()
    {
        $file = '/var/glx/weblog/event_chanel_name.' . getCurrentUserId();
        //return $file;
        if (file_exists($file)) {
            return trim(file_get_contents($file));
        }

        return 'default_pusher_chanel';
    }


    public function getSqlOrJoinExtraEdit(\Illuminate\Database\Eloquent\Builder &$x = null, $params = null)
    {
        //Kiem tra xem User hien tai co quyen khong:
        if (Helper1::isMemberModule()) {
            $eventId = intval($params['id'] ?? 0);
            //Xem su kien thuoc phong ban nao:
            $event = EventInfo::find($eventId);
            if (!$event) {
                die("Not found event! $eventId");
            }
            $email = getCurrentUserEmail();

            $depId = EventInfo::getDepartmentIdOfUser(getCurrentUserId());
            //Neu su kien khong thuoc phong ban cua User thi bao loi:
            if ($event->department != $depId) {
                die("$email, Dữ liệu không thuộc quyền của bạn (Event: $eventId)!");
            }
        }
    }

    function getSqlOrJoinExtraIndex(\Illuminate\Database\Eloquent\Builder &$x = null, $getSelect = 0)
    {
        if (Helper1::isMemberModule()) {
            $depId = EventInfo::getDepartmentIdOfUser(getCurrentUserId());
            if (!$depId) {
                $depId = -100000;
            }
            //Theem dieu kien deparemtnent_id
            $x->where('department', $depId);
            return;
        }

        return $x->leftJoin('users', 'user_id', '=', 'users.id')
            ->addSelect([
                'users.email AS _email'
            ]);
    }

    public function setDefaultValue($field)
    {
        if ($field == 'status') {
            return 1;
        }
        $domain = UrlHelper1::getDomainHostName();

        if($idf = static::getDefaultTemplateId()){

            $obj = EventInfo::find($idf);
            if($obj)
            if($mm = self::getDefaultTemplateField()){
                if(in_array($field, $mm)){
                    $val = $obj->$field;
                    if($val){
                        return $val;
                    }
                }
            }
        }

        if ($field == 'reg_mail_title_vi1') {
            return "Xác nhận đăng ký sự kiện: [EVENT_NAME]";
        }
        if ($field == 'reg_mail_title_vi2') {
            return "Đăng ký thành công sự kiện: [EVENT_NAME]";
        }

        if ($field == 'reg_mail_title_en1') {
            return "Event registration confirmation: [EVENT_NAME]";
        }
        if ($field == 'reg_mail_title_en2') {
            return "Event registration successful: [EVENT_NAME]";
        }

        if ($field == 'reg_mail_01_vi') {
            return "Xin chào [USER_NAME],
Quý vị đã đăng ký sự kiện: [EVENT_NAME]
Xin mời click vào link sau để xác nhận thông tin:
[CONFIRM_EMAIL]
Xin cảm ơn!
-------------
Mọi thông tin xin liên hệ:
https://$domain";
        }

        if ($field == 'reg_mail_02_vi') {
            return "Xin chào [USER_NAME],
Quý vị đã được duyệt đăng ký vào sự kiện: [EVENT_NAME]
Vui lòng sử dụng  mã QRCODE sau khi tham gia Sự kiện:
[QRCODE]
Xin cảm ơn Quý vị!
-------------
Mọi thông tin xin liên hệ:
https://$domain";
        }

        if ($field == 'reg_mail_01_en') {
            return "Dear Nguyen van Anh,
You are registering for event: [EVENT_NAME]
Please click the link below to confirm your registration:
[CONFIRM_EMAIL]
(Or copy and paste the link into your browser)
Thank and best regards!
-------------
For more information, please visit:
https://$domain";
        }

        if ($field == 'reg_mail_02_en') {
            return "Dear [USER_NAME],
You are approved for event: [EVENT_NAME]
Please use the following QR code to Check-in.
[QRCODE]
We will contact you soon.
Thank and best regards!
-------------
For more information, please visit:
https://$domain";
        }


    }

    public static function getIdReadOnlyIfNotSupperAdmin()
    {
        return 6;
    }

    function _image_list($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    static function htmlDivSubEventAdmin($ev1) {

        $strFullTIme = \App\Models\EventInfo::getStrTimeStartEnd($ev1);

        $padPublic = '';
        if(!$ev1->allow_public_reg){
            $padPublic = "  <div style='color: brown; font-style: italic'>Không mở Đăng ký Public</div>";
        }

        $loc = '';
        if($ev1->location)
            $loc = " | $ev1->location";
        return "<div class='sub_event_info' data-id='$ev1->id'>
 <i title='Gỡ sự kiện con này ra khỏi sự kiện cha' data-id='$ev1->id' class='fa fa-times remove_ev'
 style='float:right;color: red'> </i>
<a target='_blank' href='/admin/event-info/edit/$ev1->id'>
<b> $ev1->id. $ev1->name </b>
</a>
<br>
$strFullTIme  $loc $padPublic
</div>";
    }

    function _sub_event_list($obj, $val, $field)
    {

        $mt = new EventRegister_Meta();
        if(!Helper1::isApiCurrentRequest())
            $mt->extraCssIncludeEdit();
        $ret = "";

        $str = '';
//        $str = EventInfo::htmlSubEventInputCheck($obj, null);

        $str .= "<div class='sub_event_zone'>";
        $mm = EventInfo::where('parent_id', $obj->id)->get();
        if(count($mm)){
            foreach ($mm AS $ev1){
                $str .= static::htmlDivSubEventAdmin($ev1);
            }
        }
        $str .= "</div>";


        $ret .= "
        <div id='dynamic-select-container_child_$obj->id' class='select_to_add mb-3 mt-2' data-code-pos='ppp173059221'
        style=''>
            <select id='dynamic-select_child_$obj->id' placeholder='Choose an option...' data-code-pos='ppp160597431'>
                <option value='0' selected> --- Chọn Sự kiện con để thêm vào ---</option> <!-- Title ban đầu -->
            </select>
        </div>";

        if($str)
        $ret .= "
        <div class='sub_event_list m-0' style='border: 0px solid #ccc; padding: 0px; width: 100%' data-code-pos='ppp17356026024341'>
$str

        </div>";

//        $ret .="<A HREF='/admin/event-info' target='_blank' class=''>
//        <button type='button' class='btn btn-primary btn-sm m-2 mx-1' > THÊM SỰ KIỆN CON</button>
//        </A>
//        ";


        return $ret;
    }


    function _user_id($obj, $val)
    {
        $user = User::find($val);
        if ($user) {
            return " <div style='font-size: small; padding: 3px 10px'> $user->email </div> ";
        }
    }


    public function getFullSearchJoinField()
    {
        return ['event_infos.name'  => "like", 'location'  => "like", 'users.email'  => "like"]; // TODO: Change the autogenerated stub
    }

    public function _attached_files_email1($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    function _image_register($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    //...


    function _department($obj, $value, $field)
    {
        $m1 = Department::select(['id', 'name'])->get()->toArray();

        $mm = [];
        $mm[0] = '--- Chọn Đơn vị ---';
        foreach ($m1 as $v1) {
            $mm[$v1['id']] = $v1['name'];
        }
//        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//        print_r($mm);
//        echo "</pre>";

//        echo "<pre> >>> " . __FILE__ . "(" . __LINE__ . ")<br/>";
//        print_r($mm);
//        echo "</pre>";

        //Nếu có obj có thì mới trả lại Key=>id
        //Nếu ko, nghĩa là trường hợp Get all để chọn
        if ($obj) {
            if (isset($mm[$value]) && $value) {
                return [$value => $mm[$value]];
            } else {
                return null;
            }
        }

        return $mm;

    }

    public function _attached_files_email1_en($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _attached_files_email2($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _attached_files_email2_en($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _attached_files_email3($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _attached_files_email3_en($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _files($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }



    public function extraContentIndex1($v1 = null, $v2 = null, $v3 = null)
    {
        ?>


        <?php

    }

    public function extraContentIndex2($v1 = null, $v2 = null, $v3 = null)
    {
        ?>

        <style>



            .input_value_to_post.name {
                /*display: none;*/
                font-weight: bold;
                color: dodgerblue;
            }

            ol.breadcrumb input, ol.breadcrumb a, ol.breadcrumb button {
                padding: 0;
                margin: 0;
                border: 0;
                line-height: 1;
                font-size: 16px;
            }
        </style>

        <div style=' float: right; display: none; margin-top: 1px; border: 0px solid red ' class="mr-2">

            <!--            <i class="fa fa-cog">-->
            <!---->
            <!--            </i>-->

            <input title="Chanel Name trùng tên với trên App gửi SMS" id="chanel_name" type='text'
                   value="<?php echo EventInfo_Meta::getEventChanelName() ?>"
                   placeholder="Chanel name" class='form-control-sm'
                   style='vertical-align: bottom; display: inline-block; margin: 0px; min-height: 25px!important; height: 22px; padding: 1px 8px; color: gray; width: 100px; border: 1px solid #ccc'>


            <button type="button" id="btn_chanel_save" class=""
                    style='vertical-align: bottom; display: inline-block; border: 1px solid #ccc; font-size : smaller; padding: 5px'
                    title="Save chanel name">Save
            </button>


        </div>

        <?php
    }

    public function extraHtmlIncludeEdit1()
    {

        ?>

        <style>
            .choices__list {
                z-index: 10000000;
            }
            .btn_open_dialog_tree[data-field="parent_id"] {
                display: none;
            }
            .action_zone1
            {
                height: 44px;

                background-color: #f8f9fa ;
                /*margin: -20px -15px 15px -15px;*/
                border-radius: 5px 5px 0px 0px;
                text-align: left; display: flex; align-items: center; font-size: 110%; font-weight: bold; color: royalblue;
                padding-left: 9px;
                border-bottom: 0px solid #ccc;
            }
            .action_zone2
            {
                background-color: #f8f9fa; height: 44px;
                /*margin: 15px -15px 12px -15px;*/
                border-radius: 0px 0px;
                display: flex; align-items: center; font-size: 110%; font-weight: bold; color: royalblue;
                border-top: 1px solid #ccc;
                border-bottom: 1px solid #ccc;
                padding-left: 9px;
            }
            .action_zone11 {
                padding: 15px;
                display: block;
            }
            .action_zone21 {
                display: block;
                padding: 15px;
            }
            .action_zone21 .row {
                margin: 0px;
            }

            .action_zone21 .col-sm-6{
                padding: 0px;
            }

            .action_zone2 :hover, .action_zone1 :hover{
                cursor: pointer;
            }

        </style>


        <?php
        $this->extraCssInclude();
        $em = SiteMng::getInstance()->admin_email;
        $phone = SiteMng::getInstance()->admin_email;

        $idf = request('id');
        $meta = EventInfo::getMetaObj();
        if ($meta instanceof MetaOfTableInDb) ;
        $mmMeta = ($meta->getMetaDataApi());
        $slContMail = "<select class='select_type select_mail_content' data-ev-id='$idf'>";
        foreach ($mmMeta as $fieldName => $tmp) {
            if (str_ends_with($fieldName, 'en'))
                continue;
            if (str_starts_with($fieldName, 'content')) {
                $d1 = $meta->getDescOfField($fieldName);
                $slContMail .= " <option value='$fieldName'> $d1 </option>";
            }
        }
        $slContMail .= "</select>";

//        echo "<div class='mt-3 send_test_div'>
//<div class=''>
//$slContMail
// <input type='text' value='$em'>
//<button class='btn btn-info btn-sm ' id='send_mail_test'> Gửi thử Email Admin: </button>
//<br>
// <input placeholder='Nhap so phone...' type='text' value=''>
// <button class='btn btn-info btn-sm '> Gửi thử Sms: </button>
//</div>
//</div>";

    }


    function afterInsertApi($obj, $get = null, $post = null)
    {
        //Gan Department ID cho Event
        $obj->department = EventInfo::getDepartmentIdOfUser(getCurrentUserId());
        $obj->addLog("Tạo mới sự kiện, gán Department auto theo thong tin Phòng ban của user");
        $obj->save();

    }


    public function extraJsIncludeEdit($objData = null)
    {
//
//        $this->extraJsInclude();
        $mt = new EventRegister_Meta();
        $mt->extraJsIncludeEdit();

        require_once "EventInfo_Meta_js_edit.php"
        ?>

        <script>

            // document.addEventListener('DOMContentLoaded', function () {

                function previewField(fieldx) {
                    //Lấy nội dung tinymce của  #edit_rich_text_content1
                    var content = tinyMCE.get('edit_rich_text_' + fieldx).getContent();


                    if (!content) {
                        alert("Nội dung rỗng!");
                        return;
                    }

                    console.log("Content to preview Field: ", fieldx);
                    console.log("Content : ", content);

                    //fetch lên 1 url nội dung này, lấy kq trả về
                    var url = '/tool1/_site/event_mng/check_remove_mark_content.php';
                    $.post(url, {
                        content: content
                    }, function (data) {
                        console.log("Data," ,data);
                        // if (data.error) {
                        //     alert(data.error);
                        //     return;
                        // }
                        //Hiển thị nội dung trả về trong modal
                        $('.content_send_preview2').html(data);
                        $('#previewMessageReplaceMark').modal('show');
                    });



                    //
                    // $('.content_send_preview2').html(content);
                    // $('#previewMessageReplaceMark').modal('show');
                }
            // });


        </script>

        <?php
    }

    //...

    public function extraCssInclude()
    {
        ?>
        <style>


            input.input_value_to_post.parent_id{
                /*display: none!important;*/
            }

            span.tree_select.parent_id{
                /*display: none!important;*/
            }

            .action_event .sub {
                display: flex;
                justify-content: space-between;
            }

            .action_event {
                /*width: 1100px;*/

                border: 1px solid #ccc;
                /*padding: 20px 15px 15px 15px;*/
                background-color: white;
                text-align: left;
                font-size: 90%;
                border-radius: 5px;
                /*margin-bottom: 15px;*/
                border-bottom: 0px solid #ccc;
            }

            .select_type {
                height: 30px;
                padding-left: 10px;
                display: inline-block;
                width: 100% !important;
                border: 1px solid #ccc !important;
                margin-bottom: 10px;
            }

            input[name='action[]'] {
                display: none;
            }

            button.send_tin {
                margin-right: 5px;
            }

            .action_zone {
                text-align: center;
                border-radius: 5px;
                /*border: 1px solid #bbb!important;*/
                display: block;
                margin-bottom: 10px;
            }

            .action_zone button {
                display: inline-block;
                width: 100% !important;
            }
        </style>
        <?php
    }

    public function extraCssIncludeEdit()
    {

        ?>

        <!-- /.modal -->

        <style>

            .divTable2CellEdit[data-field-div="_sub_event_list"] div.one_item_edit{
                /*max-width: 100%!important;*/
                padding: 0px;
                margin: 10px;
            }

            .divTable2CellEdit[data-field-div="parent_id"] .select_to_add {
                max-width: 800px!important;
                /*padding: 0px 10px;*/
                margin: 0px 10px;
            }

            .choices__inner {
                /*margin: 0px 15px;*/
            }
            .choices__list--single {
                padding: 0px;
            }
            .check_sub_event{
                display: none;
            }


            .send_test_div {
                border: 1px solid #eee;
                padding: 5px;
                background-color: white;
            }

            .send_test_div select {
                padding: 5px;
                color: black;
            }


            .divTable2Body .divTable2Row {

                <?php if(Helper1::getCurrentActionMethod() == 'edit'){
                    ?>
                display: none;
                <?php
                }
                ?>
            }

            .divTable2Body .divTable2Row[data-field="parent_id"] ,  .divTable2Row[data-field="_sub_event_list"]  {
            <?php if(Helper1::getCurrentActionMethod() == 'edit'){
                ?>
                /*display: table-row;*/
            <?php
            }
            ?>
            }

            .divTable2Row.for_seperatorHeader, .divTable2Row.dummy_item {
                display: table-row;
            }

        </style>
        <?php
    }

    public function extraHtmlIncludeEdit01()
    {
//    echo "<br/>\n ABC123";
    }

    public function extraHtmlIncludeEdit0()
    {
        ?>
        <!-- Button trigger modal -->

        <!-- Modal -->
        <div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog"
        aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalCenterTitle">Chọn các thành viên của sự kiện để gửi tin</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <style>
                            .select_user select{
                                font-size: smaller;
                            }
                            .select_user option{
                                font-size: smaller;
                            }
                            .select_user input{
                                font-size: smaller;
                            }
                            .user_list td, .user_list th{
                                font-size: smaller;
                            }
                            /* Style for stacked modals */
                            .modal-backdrop + .modal-backdrop {
                                opacity: 0.15; /* Make second backdrop less opaque */
                            }
                        </style>

                        <div class="user_list mt-0">

                        </div>
                    </div>
                    <div class="modal-footer" style="font-size: smaller">
                        <div style="min-width: 300px; color: brown; padding-left: 5px" class="event_send_status_<?php echo request('id') ?>">
                        </div>
                        <span class="numberOfMemberToSend"></span>
                        <select class="form-control form-control-sm" id="message_field_send" style="width: 30%; border: 2px solid #ccc">
                            <option value="0"> - Chọn Nội dung gửi - </option>

                            <option value="content1"> Email Content 1 </option>
                            <option value="content2"> Email Content 2  </option>
                            <option value="content3"> Email Content 3  </option>
                            <option value="sms_content1"> Sms Content 1 </option>
                            <option value="sms_content2"> Sms Content 2  </option>
                            <option value="sms_content3"> Sms Content 3  </option>
                        </select>
<!--                        <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Đóng</button>-->
                        <button type="button" class="btn btn-sm btn-primary" id="sendTin2">Kiểm tra Gửi tin</button>
                    </div>
                </div>
            </div>
        </div>

                <!-- Modal -->
        <div class="modal fade " id="previewMessage" tabindex="-1" role="dialog"
        aria-labelledby="previewMessage" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Kiểm tra nội dung Tin sẽ gửi</h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" style="padding: 0px">
                        <div class="content_send_preview mt-0" style="height: 400px; overflow-y: auto; border: 0px solid #eee; padding: 10px 0px 10px 10px">
                        </div>
                    </div>
                    <div class="modal-footer" style="font-size: smaller">
                        <span class="numberOfMemberToSend"> ... </span>
                        <button type="button" class="btn btn-sm btn-primary" id="sendTin3">Gửi tin</button>
                    </div>
                </div>
            </div>
        </div>


        <div class="modal fade " id="previewMessageReplaceMark" tabindex="-1" role="dialog"
             aria-labelledby="previewMessage" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Kiểm tra nội dung Tin khi đã bỏ đi các dòng bắt đầu bằng <b> ### </b> </h5>
                        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" style="padding: 0px">
                        <div class="content_send_preview2 mt-0" style="height: 400px; overflow-y: auto; border: 0px solid #eee; padding: 20px">
                        </div>

                    </div>
                    <div class="m-3" style="font-size: smaller; color: royalblue; border-top: 1px solid #eee; padding-top: 10px">

                        Xem trước Nội dung trước khi gửi - khi bỏ các dòng bắt đầu bằng <b> ### </b>
                        <br>
                        Nếu chưa bỏ được dòng, hãy copy nội dung ra Notepad rồi Lại chọn Tất cả , Copy lại paste lại vào đây, edit lại nội dung!
                        <br>
                        Nguyên nhân là do edit dạng web phức tạp, nhiều mẫu không nhận ra được khi thay đổi nhiều.
                    </div>


                </div>
            </div>
        </div>

        <?php
        if (!request('id'))
            return;;
        $obj = EventInfo::find(request('id'));

        $domain = UrlHelper1::getDomainHostName();
        $module = Helper1::getModuleCurrentName();

        if (getCurrentActionMethod() !== 'edit') {
//            return "Sau khi tạo sự kiện ta có thể Thao tác (SMS, Email...)";
        }


        $mUserSend = EventAndUser::where('event_id', $obj->id)->get();
        $tt = count($mUserSend);
        $fromMail = SiteMng::getEmailAdmin();
        $fromName = SiteMng::getSiteCode();
        $uidL = '';
        $nTuChoi = $nCoMat = $nThamGia = 0;
        foreach ($mUserSend as $ue) {
            if ($ue->confirm_join_at) {
                $nThamGia++;
            }
            if ($ue->deny_join_at) {
                $nTuChoi++;
            }
            if ($ue->attend_at) {
                $nCoMat++;
            }

            $uidL .= "$ue->user_event_id,";
        }

        //  /admin/event-user-info?seby_s1=11&seoby_s1=eq

        $uidL = trim($uidL, ',');

        $ret = "<div class='action_event' data-id='$obj->id' style=''> ";

        $ret .= "<div class='action_zone1'><i class='nav-icon fa fa-plus-circle mr-1'></i>
THEO DÕI QUẢN LÝ KHÁCH THAM DỰ
<i class='open_all_tab fa fa-arrow-down ml-2' style='color: brown' title='Mở tất cả các Tab khác'></i>
</div> ";


        if (getCurrentActionMethod() === 'edit') {


            $ret .= " <span></span> ";
        }


        $ret .= "<div class='action_zone11'> <div class='sub'>";
//            $ret .= "<a
//title = 'Xem danh sách sự kiện + user'
// target='_blank' href='/admin/event-and-user?seby_s4=$obj->id'>
//<button class='btn btn-primary  btn-sm'>
//<i class='fa fa-external-link-alt'></i>
//User & Actions
//</button>
//</a>";

            $ret .= "
<a href='/$module/event-user-info?_add_user_to=$obj->id' title='Thêm thành viên vào sự kiện'>
<button class='btn btn-primary btn-sm'>
<i class='fa fa-plus'></i>
Thêm ĐB
</button>
</a>
";


            if ($uidL) {
                $ret .= "&nbsp&nbsp
               <a
               title = 'Xem danh sách chi tiet user'
               href='/$module/event-user-info?_event_id_=$obj->id'>

            <button class='btn btn-primary  btn-sm'>
            <i class='fa fa-users'></i>
            Thông tin về ĐB
            </button>
            </a>
                ";
            }

            $ret .= "&nbsp&nbsp
               <a
               title = 'Xem bảng user gắn với sự kiện'
               href='/$module/event-and-user?seby_s5=$obj->id'>

            <button class='btn btn-primary  btn-sm'>
            <i class='fa fa-users'></i>
             Xếp chỗ ĐB
            </button>
            </a>
                ";

            $ret .= " &nbsp&nbsp
 <a
title = 'Duyệt thành viên vào sự kiện'
 href='/$module/event-register?seby_s11=$obj->id'>
<button class='btn btn-primary btn-sm'>
<i class='nav-icon fa fa-plus-circle'></i> Duyệt online
</button>
</a>";

//            $ret .= " &nbsp&nbsp
// <a
//title = 'Report this event'
// target='_blank' href='/admin/event-info/report?id=$obj->id'>
//<button class='btn btn-primary btn-sm'>
//<i class='nav-icon fa fa-cog'></i> Báo cáo Public
//</button>
//</a>";

            $ret .= " &nbsp&nbsp
 <a
title = 'Report this event'
  href='/$module/event-info/report-sum?id=$obj->id'>
<button class='btn btn-primary btn-sm'>
<i class='nav-icon fa fa-cog'></i> Báo cáo tổng
</button>
</a>";


            $ret .= " &nbsp&nbsp <a
title = 'Log SMS, Email'
  href='/$module/event-send-info-log?seby_s4=$obj->id'>
<button class='btn btn-primary  btn-sm'>
<i class='fa fa-list'></i> Nhật ký gửi tin
</button>
</a>";

        $ret .= " &nbsp&nbsp <a
title = 'Log SMS, Email'
  href='/admin/event-user-payment?seby_s5=$obj->id'>
<button class='btn btn-primary  btn-sm'>
<i class='fa fa-usd'></i> Thanh toán
</button>
</a>";

            $ret .= "</div>";
//            $ret .= "</div ...>";
//            $ret .= "<div class='sub'>";



            $cmd = '/var/www/html/public/tool1/_site/event_mng/send_event_sms_mail_loop.php';
            $linkLog = '';
//        if (Helper1::isAdminModule())
//            $linkLog = "  <a href='/tool1/_site/event_mng/read_log_file_event.php' target='_blank'> Xem Log File </a>";

            $linkSendCmd = " | <a href='/$module/event-send-action?seby_s11=$obj->id' target='_blank'> Các lệnh Gửi tin </a>";
            $runningScript = "$cmd";
            exec("ps aux | grep $runningScript |grep -v grep", $output);

            if (str_contains(serialize($output), $cmd))
                $ret01 = "<div class='py-2 pr-2 mb-1 ml-0' style='color: green; display: inline-block; margin-top: 0px; '>
<span style='padding-top: 2px; display: inline-block'>Tiến trình gửi Email đang hoạt động
</span>
  $linkLog $linkSendCmd </div>";
            else
                $ret01 = "<DIV class='mt-3 py-1 px-2 bg-danger' style='color: red; float: right'> Cánh báo: Tiến trình Gửi Email KHÔNG HOẠT ĐỘNG,
các lệnh gửi SMS, Email sẽ chạy khi tiến trình hoạt động $linkLog ! <br>
 Hãy chạy lệnh: <b> glxNcbdMailSend </b> tại dòng lệnh trên server
 </DIV> <br> $linkLog $linkSendCmd ";



            $ret .= "<div class='mt-3 mb-2' style='border-bottom: 0px solid #ccc; padding-bottom: 10px; display: flex; justify-content: space-between' >
<button class='btn btn-default btn-sm'> Số thành viên: <span class='badge bg-primary'> $tt </span> </button> ";
            $ret .= "<button class='btn btn-default btn-sm'>Xác nhận tham gia: <span class='badge bg-primary'> $nThamGia</span> </button> ";
            $ret .= "<button class=' btn btn-default btn-sm'>Từ chối tham gia: <span class='badge bg-primary'>$nTuChoi</span> </button>";
            $ret .= "<button class=' btn btn-default btn-sm'>Đã check-in: <span class='badge bg-primary'> $nCoMat </span></button>";
            $ret .= '</div>';

            $idEvEnc = qqgetRandFromId_($obj->id);
            $linkReg = "https://$domain/event-register/$idEvEnc";
            $ret .= "<div style='width: 100%; margin-bottom: 10px; '> Link để khách Đăng ký sự kiện này: <a target='_blank' href='$linkReg'>$linkReg</a>  </div>";

            $ret .= "</div zone11>";

            $padButton = '';
            //if(isDebugIp())
                $padButton = '';

            $ret .= "

<div style='' class='action_zone2'>
    <i class='nav-icon fa fa-plus-circle mr-1'></i>
     LIÊN HỆ, THÔNG TIN VỚI KHÁCH
</div> ";

            $ret .= "<div class='action_zone21' style='width: 100%;   border: 0px solid red'>";
            $ret .= "

    <div class='row'>
        <div class='col-sm-6'>
             <button type='button' style='margin-top: 2px;' class='btn btn-sm btn-primary ' data-bs-toggle='modal' data-bs-target='#exampleModalCenter'> Quản lý gửi tin</button>
        </div>

        <div class='col-sm-6'>
            $ret01
        </div>
    </div>

 ";





            $ret .= "<div style='width: 100%; margin-bottom: 10px; display: none1 '>";




        if (getCurrentActionMethod() === 'index') {
            $ret .= ' <a href="/$module/event-info/edit/' . $obj->id . '"> <button class="btn btn-sm btn-info" type="button"> CHI TIẾT </button> </a>';
        } else {

            $mailToSend = request('mail_to_send');

            $ret .= '<textarea placeholder="Nhập danh sách user muốn gửi tin bằng cách nhập các email, cách nhau dấu phẩy.
(nếu có DS này, thì sẽ chỉ gửi Email, SMS theo DS này)"
id="user_email_send_override" style=" display: none; border: 1px solid #ccc; width: 100%; height: 80px; padding: 5px; margin-top: 5px">' . $mailToSend . '</textarea>';

            $slUser = "<select class='select_type select_user_type' data-ev-id='$obj->id'>
<option value='all_user'>
--- Tới tất cả ---
</option>
<option value='only_not_yet_confirmed_user'>
--- Khách chưa xác nhận tham dự (Chưa bấm Link) ---
</option>
<option value='only_confirmed_user'>
--- Khách đã xác nhận tham dự (Đã bấm Link) ---
</option>
<option value='only_not_attended_user'>
--- Khách chưa Check-in  (chưa Quét QR) ---
</option>
<option value='only_attended_user'>
--- Khách đã Check-in (đã Quét QR) ---
</option>
<option value='only_confirmed_but_not_checkin'>
--- Khách xác nhận Tham dự & Chưa check-in ---
</option>
<option value='only_denied_user'>
--- Khách từ chối tham dự (Bấm link Từ chối) ---
</option>
<option value='only_list_user'>
--- Lựa chọn danh sách ---
</option>

</select>
";
            $meta = $obj::getMetaObj();
            if ($meta instanceof MetaOfTableInDb) ;
            $mmMeta = ($meta->getMetaDataApi());
            $slContMail = "<select title='Ở đây không cần chọn ngôn ngữ EN, vì PM tự nhận ngôn ngữ content tương ứng user khi gửi' class='select_type select_mail_content' data-ev-id='$obj->id'>";
            foreach ($mmMeta as $fieldName => $tmp) {
                //Không cần chọn en, vì script đã tự select theo user
                if (str_ends_with($fieldName, 'en'))
                    continue;
                if (str_starts_with($fieldName, 'content')) {
                    $d1 = $meta->getDescOfField($fieldName);
                    $slContMail .= " <option value='$fieldName'> $d1 </option>";
                }
            }

            $slContMail .= "</select>";

            $slContSms = "<select class='select_type select_sms_content' name='abc' data-ev-id='$obj->id'>";

            foreach ($mmMeta as $fieldName => $tmp) {
                //Bỏ qua tiếng anh, vì TA sẽ tự đông chọn theo từng user
                if (str_ends_with($fieldName, 'en'))
                    continue;
                if (str_starts_with($fieldName, 'sms_content')) {
                    $d1 = $meta->getDescOfField($fieldName);
                    $slContSms .= " <option value='$fieldName'> $d1 </option>";
                }
            }

//        $d1 = $meta->getDescOfField('sms_content1');
//        $slContSms.=" <option value='sms_content1'> $d1 </option>";
//        $d2 = $meta->getDescOfField('sms_content2');
//        $slContSms.=" <option value='sms_content2'> $d2 </option>";
//        $d3 = $meta->getDescOfField('sms_content3');
//        $slContSms.=" <option value='sms_content3'> $d3 </option>";

            $slContSms .= "</select>";

//            $ret .= "<div class='row'>";

            $ret .= "<div style='margin-top: 0px' data-code-pos='ppp17437412299491' data-ev-id='$obj->id'>

<div class='row'>
    <div class='action_zone col-sm-6'>
        <div style='float: left; text-align: left' class='mt-2'>
          Cấu hình gửi mail: Gửi từ <b>  $fromMail</b>, Tên: <b>   $fromName </b>    <a target='_blank' href='/admin/site-mng/edit/1'>  [Thay đổi] </a>
        </div>
    </div>

    <div class='action_zone col-sm-6'>
        <div style='float: left; text-align: left' class='mt-2'>
            <div id='status_app' style=''> [Đang lấy trạng thái App SMS] </div>
            </div>
        </div>
    </div>

</div>




<div class='row' style='display: none'>
<div class='action_zone col-sm-6'>

$slUser
 <br>
 $slContMail
<br>
<button type='button'  style='text-align: center; font-size: small' class='send_tin email btn btn-primary btn-sm'> Gửi Email</button>

<div style='float: left; text-align: left' class='mt-2'>
  Cấu hình gửi mail: Gửi từ <b>  $fromMail</b>, Tên: <b>   $fromName </b>    <a target='_blank' href='/admin/site-mng/edit/1'>  [Thay đổi] </a>
</div>
</div>


<div class='action_zone  col-sm-6' data-code-pos='ppp17334468351691'>

        $slUser
        <br>
        $slContSms
        <br>
        <button type='button'  style='text-align: center; font-size: small; ' class='send_tin sms btn btn-primary btn-sm'> Gửi Sms</button>

        <div style='float: left; text-align: left' class='mt-2'>
            <div id='status_app' style=''> [Đang lấy trạng thái App SMS] </div>
            </div>
        </div>

        </div>






        ";
//            $ret .= "
//<div class='action_zone'>
//<button type='button' style='text-align: center; font-size: small' class='stop_send_tin btn btn-warning btn-sm'> Dừng gửi</button>
//</div>
//";

            $ret .= '</div>';

            $done = '';
            if ($evs = EventSendAction::where(['event_id' => $obj->id])->first()) {
                if ($evs->done) {
//                $done = ' Đã gửi thành công !';
                }
            }

            $ret .= '<div style="margin-top: 5px; padding: 5px; background-color: lavender; color: dodgerblue">
<div style="min-width: 300px; color: brown; padding-left: 5px" class="event_send_status_' . $obj->id . '">
</div>' . $done . '</div>';

        }

        $ret .= "</div>";

//        $ret .= "<button type='button'  style='text-align: center; font-size: small;' data-ev-id='$obj->id' class='sync_sms sms btn btn-primary btn-sm'
//title='Đồng bộ Tin nhắn sms Từ app trên mobile lên Database trên server. Hãy bật App trên Mobile, và kiểm tra chế độ đã kết nối trên App, sau đó bấm nút Đồng bộ này'
//
//> Sync Sms</button>";


//        if(isSupperAdmin_())
        {
//            $ret .= "<div id='status_app' style=''> ... </div>";
        }


        $ret .= '</div>';

        echo $ret;
//        return $ret;
?>

        <?php
    }

    function _parent_id($obj, $val, $field){
//        return "ABC";

        if(Helper1::getCurrentActionMethod() == 'index')
            return;
        ?>
        <?php

        $retP = parent::_parent_id($obj, $val, $field);

        $ret = "
        <div id='dynamic-select-container_$obj->id' class='select_to_add mb-3' data-code-pos='ppp17356059221'>
            <select id='dynamic-select_$obj->id' placeholder='Choose an option...' data-code-pos='ppp16059857431'>
                <option value='0' selected> --- Chọn sự kiện cha ---</option> <!-- Title ban đầu -->
            </select>
        </div>";

        return $ret;
    }

    function _name($obj, $val)
    {
//        return "<div class='mx-2' style=' display: inline-block; font-size: 80%; white-space: nowrap;   overflow: hidden;    text-overflow: ellipsis; '><a  href='/admin/event-info/edit/$obj->id'> $obj->name </a></div>";

    }

    public function extraJsInclude() {
        ?>

        <style>

           div.select_to_add {

                background: snow;
                padding: 1px 5px!important;
                display: block!important;
                border: 0px dashed #ccc!important;
            }

            .input_value_to_post.name:hover {
                cursor: pointer;
            }
        </style>
        <script>
            $(".input_value_to_post.name").click(function (){
                let dataId = $(this).attr('data-id');
                location.href = "/admin/event-info/edit/" + dataId;
            })
            // $(".divTable2Cell[data-table-field=name]").click(function (){
            //     let dataId = $(this).attr('data-id');
            //     location.href = "/admin/event-info/edit/" + dataId;
            // })
        </script>
        <?php
    }

    function afterZoneFieldEdit($field, $obj = null)
    {

        if($field == 'time_start_check_in'){

//        return "ABC123";

        }


    }

    function preZoneFieldEdit($field, $obj = null)
    {
//        return;
//        if(!isIPDebug()){
//            return;
//        }

        $ret = '';

        if($field == 'id'){
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i>THÔNG TIN CƠ BẢN VỀ SỰ KIỆN";
        }

        if($field == 'sms_content1'){
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i> NỘI DUNG SMS ";
        }

        if($field == 'mail_title1'){
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i> NỘI DUNG EMAIL";
        }

//        if($field == 'reg_mail_title_vi1')
        if($field == 'allow_public_reg')
        {
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i>  CÀI ĐẶT - OPTIONS";
        }

        if($field == 'user_id') {
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i>  THÔNG TIN KHÁC";
        }

        if($field == 'parent_id') {
            return $ret = "<i class='nav-icon fa fa-plus-circle mr-1'></i>    CÀI ĐẶT SỰ KIỆN CHA - CON";
        }


        return $ret;
    }


}
