<?php

namespace App\Models;

use LadLib\Common\Database\MetaOfTableInDb;
use LadLib\Common\UrlHelper1;

class FileUpload_Meta extends MetaOfTableInDb
{
    protected static $api_url_admin = '/api/admin-file';

    protected static $api_url_member = '/api/member-file';

    protected static $web_url_admin = '/admin/file';

    protected static $web_url_member = '/member/file';

    public static $folderParentClass = FolderFile::class;

    public static $titleMeta = "Danh sách Files";

    public static $modelClass = FileUpload::class;

    protected static $index_view_member = 'member.file.index';

    public static $disableAddItem = 1;
    public function isUseRandId()
    {
//        if(\App\Models\SiteMng::getDbName() == env('DB_DATABASE_GLX_TESTING'))
//            return 0;

        return SiteMng::isEncodeIdCloud();
    }

    public function getAllFieldBelongUserId()
    {
        return ['parent_id' => FolderFile::class];
    }

    function _cloud_id($obj, $val, $field){

        $fid = $obj->id;
        if(!$val)
            $val = $fid;

        return "<div class='mx-2 small' data-code-pos='ppp17387171550011'> <a target='_blank' href='/admin/file-cloud/edit/$val'> Cloud </a> </div>";
    }

    function _user_id($obj, $val, $field){
        $user = User::find($val);
        if($user)
            return "<div class='mx-2 small'> <a target='_blank' href='/admin/user/edit/$val'> $user->email </a> </div>";
    }

    public function afterInsertApi($obj,$get = null,$post = null){

        if(isCli()){
//
//            dump($obj->toArray());
//            die('1111111111111111');
        }

//        parent::afterInsertApi($obj,$get,$post); // TODO: Change the autogenerated stub
    }

    public function extraJsInclude()
    {
    ?>
        <script src="/admins/upload_file.js"></script>

        <script>
            let objUpload = new clsUploadV2()

            objUpload.url_server = '/api/member-file/upload';
            objUpload.bind_selector_upload = 'upload_admin_zone';
            // objUpload.bind_selector_result = 'result-area-upload';
            // objUpload.bind_div_upload_status_all = 'div_upload_status_all';

            objUpload.upload_queue = 0;
            objUpload.uploading = 0;
            objUpload.upload_done = 0;
            objUpload.upload_total = 0;
            objUpload.upload_error = 0;
            objUpload.maxFileCC = 2;
            objUpload.bearerToken = jctool.getCookie('_tglx863516839');
            objUpload.maxSizeUpload = <?php echo \App\Models\SiteMng::getMaxSizeUpload()?>;

            let sField = '<?php echo $searchField = \App\Models\FileUpload_Meta::getSearchKeyFromField('parent_id'); ?>';
            if (jctool.getUrlParam(sField))
                objUpload.set_parent_id = jctool.getUrlParam(sField);

            objUpload.mFileUpload = [];

            $(function (){
                objUpload.initUpload()
            })

        </script>



        <?php

    }

    function _parent_id($obj, $valIntOrStringInt, $field)
    {
        if(isDebugIp()){
//            echo "PID = $valIntOrStringInt xxx.";
//            if(isUUidStr($valIntOrStringInt))
//                $valIntOrStringInt = FolderFile::where("ide__", $valIntOrStringInt)->first()?->id;
        }
        return parent::_parent_id_template($obj, $obj->parent_id, $field); // TODO: Change the autogenerated stub

    }

    function _file_size($obj, $val)
    {
        return "<div style='text-align: right; font-size: 90%; margin-right: 10px'>" . ByteSize($val) . "</div>";
    }

    public function extraContentIndex1($v1 = null, $v2 = null, $v3 = null)
    {
        \App\Models\FileUpload_Meta::includeUploadZoneHtmlSample("upload_admin_zone");
    ?>
        <link rel="stylesheet" href="/admins/upload_file.css?v=1725510479">

        <?php
    }

    public function getNeedIndexFieldDb()
    {
        $fields = [
            'id',
//            'id__',
            'ide__',
            'cloud_id',
            'parent_id',
            'user_id',
            'refer',
            'link1',
            'md5',
            'crc32',
            'deleted_at'
        ];
        return $fields  ;
    }

    public function getRandIdListField($field = null)
    {
        return ['id', 'parent_id'];
    }

    public function getHardCodeMetaObj($field)
    {

        $objMeta = new MetaOfTableInDb();

        //Riêng Data type của Field, Lấy ra các field datatype mặc định
        //Nếu có thay đổi sẽ SET bên dưới
        $objSetDefault = new MetaOfTableInDb();
        $objSetDefault->setDefaultMetaTypeField($field);

        $objMeta->dataType = $objSetDefault->dataType;

        if ($field == 'parent_id') {
            $objMeta->dataType = DEF_DATA_TYPE_TREE_SELECT;
            $objMeta->join_api = '/api/member-folder-file';
            //            $objMeta->join_func = 'App\Models\DemoFolderTbl::joinFuncPathNameFullTree';
        }


        return $objMeta;
    }


    public function _name($obj, $name, $field)
    {

        if(!$obj->link1){
//            $obj->link1 = 'ms'.eth1b($obj->id);
//            $obj->save();
        }

        if(SiteMng::enable4sLink()) {
//            $obj1 = FileUpload::find($obj->id);
//            if($obj1 instanceof FileUpload);
//            $obj1->getLink1(1);
            $domain = UrlHelper1::getDomainHostName();
            $link = "https://$domain/f/$obj->link1";
            return "<a target='_blank' data-code-pos='ppp17274075357591' style='margin-left: 10px; font-size: smaller' href='$link'> $link </a>";
        }
        if(SiteMng::enableDocumentEditor()) {
            $link = "/tool/drive/edit-file.html?fide=" . qqgetRandFromId_($obj->id);
            $ext = pathinfo($obj->name, PATHINFO_EXTENSION);
            if(in_array($ext, ['doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'pdf'])) {

                if(in_array($ext, ['doc', 'docx'])) {
                    $ic1 = "<i class='fas fa-file-word fa-2x pt-1' style='color: blue'></i>";
                }
                if(in_array($ext, ['xls', 'xlsx'])) {
                    $ic1 = "<i class='fas fa-file-excel fa-2x pt-1'  style='color: green'></i>";
                }
                if(in_array($ext, ['ppt', 'pptx'])) {
                    $ic1 = "<i class='fas fa-file-powerpoint fa-2x pt-1'  style='color: royalblue'></i>";
                }
                if(in_array($ext, ['pdf'])) {
                    $ic1 = "<i class='fas fa-file-pdf fa-2x pt-1'  style='color: saddlebrown'></i>";
                }

                return " &nbsp <a target='_blank' data-code-pos='ppp172740753591' style='font-size: smaller' href='$link'> $ic1 Edit Document </a>";
            }
        }

        //return $this->_id($obj, $obj->id, $field);
    }

    public function setEncodeIdRand()
    {
        return 1;
    }

    public function _id($obj, $id, $field)
    {

        //        $obj = FileUpload::find($id);
        //        if(!$obj)
        //            return ("Not found $id");
        if ($obj instanceof FileUpload);
        $linkThumb = $obj->getCloudLinkImage();
        $linkDl = $obj->getCloudLink();

        $mime = $obj->mime;
        $mime0 = substr($mime, 0, 6);

        $filePath = $obj->file_path;
        $ok = "";
        if(0)
        if(file_exists($filePath)){
            if(!$cl = FileCloud::find($obj->cloud_id)){
//                echo "\n Need Cloud";
                $cl = new FileCloud();
                $cl->name = $obj->name;
                $cl->id = $obj->cloud_id;
                $cl->size = $obj->file_size;
                $cl->md5 = md5_file($filePath);
                $cl->file_path = $filePath;
                $cl->save();
            }
            else{
                $ok = "Found Cloud";
//                echo "\n Found Cloud";
            }


        }

        if (! $mime || strstr($mime, 'image') !== false) {
            $img = "$ok <img data-code-pos='ppp1668517832984' data-src='$linkThumb' class='file_link_cloud'
 style='margin-top:5px; max-height: 120px;max-width: 120px;' src='$linkThumb'/> ";
        } else {
            $mime = substr($mime,0,20);
            $mime = '';
            $img = "<div data-code-pos='ppp17305336251621' style='font-size: x-small; padding: 5px; background-color: lavender; border: 1px solid #eee'> Download <br> $mime</div>";
        }

        if (request('browse_file_iframe')) {
            return " <div style='text-align: center'>$img</div>";
        }

        return " <div style='text-align: center'> <a href='$linkDl' target='_blank'>$img </a> </div>";
    }

    public function requireViewPos1()
    {
        echo "<br/>\n xxxx1";
    }


    function preZoneFieldEdit($field, $obj = null)
    {

    }

    public static function includeUploadZoneHtmlSample($idZoneUpload, $accept = '*/*')
    {

        $idStatus = 'upload_status_all_'.$idZoneUpload;
        //        $idFileElm = 'upload_fileElem_' . $tag;

        ?><div data-code-pos='ppp17343990082141' style="margin-top: 10px; padding: 1px 10px; font-size: small; float: right; margin-right: 10px; margin-bottom: 5px">
            <?php
            $uid = getCurrentUserId();
            if ($uid) {
                $gpUser = FileUpload::createQuotaUser($uid);
                if (! $gpUser) {
                    loi("Not found quota for user! $uid");
                }

                $bs = ByteSize($gpUser->quota_size);
                $countUsing = FileUpload::where('user_id', $uid)->count();
                $sumByteUsing = FileUpload::where('user_id', '=', $uid)->sum('file_size');
                $bs1 = ByteSize($sumByteUsing);

                $percent = number_format($sumByteUsing * 100 / $gpUser->quota_size, 2);

                ?>
                <div style="">
                    <div data-code-pos="ppp1682474951457" style="background-color:#ccc; width: 100px; display: inline-block">
                        <div style="width:<?php echo $percent ?>%; background-color:dodgerblue; padding: 2px 5px; color: white ; text-align: center">
                            <?php echo $percent ?>%
                        </div>
                    </div>
                    <?php

                    $maxSize0 = SiteMng::getMaxSizeUpload();
                    $maxSize = ByteSize($maxSize0, 0);

                    echo " &nbsp Đã dùng <b>$bs1</b> ($countUsing file) | Giới hạn: <b>$bs</b> ($gpUser->quota_file file)  ".
                        "| Cỡ file tối đa: <b> $maxSize </b>";
                    ?>
                </div>
                <div style="clear: both"></div>
                <?php

                if ($gpUser->quota_size <= $sumByteUsing) {
                    echo "<span style='color: red; font-weight: bold'> Bạn đã sử dụng quá dung lượng cho phép: ".ByteSize($sumByteUsing).' > '.ByteSize($gpUser->quota_size).'. </span>';
                }
                if ($gpUser->quota_file <= $countUsing) {
                    echo " <span style='color: red; font-weight: bold'> Bạn Đã sử dụng quá số file cho phép: $countUsing > $gpUser->quota_file . </span>";
                }

            }
            ?>
        </div>
<!--        End ppp17343990082141-->
        <div class="upload_zone_glx" id="<?php echo $idZoneUpload?>">



            <div data-code-pos="ppp1668068062735"  title="drag drop file here" class="drop_area upload_area">
                <form class="my-form">
                        <span style="float: right; font-style: italic">
                            <span style="font-size: small" data-id="upload_info">
                            </span>
                        </span>
                    <input class="file_elm_upload" type="file" id="<?php echo $idZoneUpload?>_file" multiple accept="<?php echo $accept ?>"
                           onchange="clsUploadV2.handleFiles(this, this.files, <?php echo $maxSize0 ?> )">
                    <label class="upload_button" for="<?php echo $idZoneUpload?>_file">Upload Files</label>
                </form>
                <div class="upload_status_some" data-id="<?php echo $idStatus?>">
                </div>
            </div>
            <div class="upload_result_all" style="display: none"></div>
        </div>
<!--        END upload_zone_glx -->
        <?php
    }

    public function extraCssInclude()
    {
        ?>
        <style>

        div[data-table-field="count_download"] input{
           text-align: center;
        }

        input.input_value_to_post.file_size {
            display: none;
        }
        input.input_value_to_post.comment {
            width: 150px!important;
        }
        </style>
        <?php
    }
}
