<?php

namespace App\Models;

use App\Components\Helper1;
use LadLib\Common\Database\MetaOfTableInDb;

/**
 * ABC123
 *
 * @param  null  $objData
 */
class HrEmployee_Meta extends MetaOfTableInDb
{
    protected static $api_url_admin = '/api/hr-employee';

    protected static $web_url_admin = '/admin/hr-employee';

    protected static $api_url_member = '/api/member-hr-employee';

    protected static $web_url_member = '/member/hr-employee';

    public static $folderParentClass = HrOrgTree::class;

    public static $modelClass = HrEmployee::class;

    public static $allowAdminShowTree = 1;

    /**
     * @return MetaOfTableInDb
     */
    public function getHardCodeMetaObj($field)
    {
        $objMeta = new MetaOfTableInDb();
        if ($field == 'status' || $field == 'admin_this_tree') {
            $objMeta->dataType = DEF_DATA_TYPE_STATUS;
        }

        if (in_array($field, ['str1', 'str2', 'str3', 'str4', 'str5', 'str6', 'str7', 'str8', 'str9', 'str10'])) {
            $objMeta->dataType = DEF_DATA_TYPE_IS_MULTI_IMAGE_BROWSE;
        }
        if ($field == 'parent_id' || $field == 'parent2') {
            $objMeta->dataType = DEF_DATA_TYPE_TREE_SELECT;
            $objMeta->join_api = '/api/hr-org-tree';
            //            $objMeta->join_func = 'App\Models\DemoFolderTbl::joinFuncPathNameFullTree';
        }

        if ($field == 'sex' || $field == 'group_time') {
            $objMeta->dataType = DEF_DATA_TYPE_HTML_SELECT_OPTION;
        }

        if ($field == 'image_list') {
            $objMeta->dataType = DEF_DATA_TYPE_IS_MULTI_IMAGE_BROWSE;
        }
        if ($field == 'work_status' || $field == 'job_title') {
            $objMeta->dataType = DEF_DATA_TYPE_HTML_SELECT_OPTION;

        }
        if ($field == 'tag_list_id') {
            $objMeta->join_api_field = 'name';
            //          $objMeta->join_func = 'joinTags';
            //HrEmployee edit, tag sẽ ko update được?
            $objMeta->join_relation_func = 'joinTags';
            $objMeta->join_api = '/api/tags/search';
            $objMeta->dataType = DEF_DATA_TYPE_ARRAY_NUMBER;
        }

        if ($field == 'user_id') {
            $objMeta->join_api_field = 'email';
            //            $objMeta->join_func = 'joinUserEmailUserId';
            $objMeta->join_api = '/api/hr-employee/search_user';
        }

        return $objMeta;
    }

    public function _parent_id($obj, $valIntOrStringInt, $field)
    {
        //return " $val , $obj->id , $obj->parent ";

        //        if($field == 'parent_multi' || $field == 'parent_multi2')
        return parent::_parent_id_template($obj, $valIntOrStringInt, $field); // TODO: Change the autogenerated stub
        /*
                if(!$valIntOrStringInt)
                    return null;

                $cls = get_called_class();

                $objFolder = new HrOrgTree();

                if($objFolder instanceof HrOrgTree);
                $ret = '';
                $retApi = [];
                //if(strstr($valIntOrStringInt, ','))
                if($valIntOrStringInt)
                {
                    $valIntOrStringInt = trim(trim($valIntOrStringInt,','));
                    $mVal = explode(",", $valIntOrStringInt);


                    if($mm = $objFolder->whereIn("id", $mVal)->get()){
                        foreach ($mm AS $obj) {
                            $mName = $obj->getFullPathParentObj(2);
                            $retApi[$obj->id] = $obj->name;
                            $retApi[$obj->id] = $name0 = implode("/", $mName);;
                            $ret .= "<span class='one_node_name' title='remove this: $obj->id' data-id='$obj->id' data-field='$field'> [x] $name0</span>";
                        }
                    }

                }

                if(Helper1::isApiCurrentRequest())
                    return $retApi;
        //        else
        //            return "xxxxxx <span title='' class='all_node_name' data-field='$field'>$ret </span>";

                return $ret;
        */
    }

    public function _user_id($obj, $val, $field)
    {
        $user = User::find($val);
        if ($user) {
            $em = substr($user->username, 0, 11);

            return " <div data-code-pos='ppp168247521371' style='font-size: small; padding: 3px'> <a target='_blank' title='$user->username' href='/admin/user-api/edit/$user->id'>$val. $em... ($user->email)</a> ".
"<span data-autocomplete-id='$obj->id-$field' class='span_auto_complete' data-item-value='$val' title='Remove this item'> x</span>  </div> ";
        }
    }

    public function _group_time($obj, $value, $field)
    {
        $mm = [
            0 => '-Nhóm giờ-',
            1 => 'Full Tuần',
            2 => 'Nghỉ Ngày T7+CN',
            3 => 'Nghỉ Chiếu T7+ CN',
            4 => 'Nghỉ chủ nhật',
        ];

        return $mm;
    }

    public function _work_status($obj, $value, $field)
    {
        $mm = [
            0 => '-TTCV-',
            1 => 'Đang Đi làm ',
            2 => 'Nghỉ',
            3 => 'Chờ',
            4 => 'Không rõ',
        ];

        //Nếu có obj có thì mới trả lại Key=>id
        //Nếu ko, nghĩa là trường hợp Get all để chọn
        if ($obj) {
            if (isset($mm[$value]) && $value) {
                return [$value => $mm[$value]];
            } else {
                return null;
            }
        }

        return $mm;
    }

    public function _sex($obj, $value, $field)
    {

        return [0 => '-chọn-', 1 => 'Nam', 2 => 'Nữ'];
    }

    public function _job_title($obj, $value, $field)
    {

        $ret = HrJobTitle::where('status', 1)->get();
        $mm = [];
        $mm[0] = '- Chức danh -';
        foreach ($ret as $obj) {
            //            echo "\n $obj->id / $obj->name ";
            $mm[$obj->id] = $obj->name;
        }

        return $mm;
    }

    public function _image_list($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str1($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str2($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str3($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str4($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str5($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str6($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str7($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str8($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function _str9($obj, $val, $field)
    {
        return Helper1::imageShow1($obj, $val, $field);
    }

    public function extraContentIndex1($v1 = null, $v2 = null, $v3 = null)
    {
        ?>
        <div data-code-pos='ppp16869058485191' style="padding-bottom: 10px; border-bottom: 1px solid #ccc; margin: 2px 8px 10px 8px">
            <button type="button" class="btn btn-info  btn-sm" id="print_multi_card"> In Thẻ </button>

        <?php
        $m1 = date('Y-m');
        echo " <button type='button' class='btn btn-info  btn-sm' href='/admin/hr-salary-month-user/report2?month=$m1' id='show_report'> Bảng Lương Tổng Hợp </button> ";

        echo '</div>';
    }

    public function extraHtmlIncludeEditButtonZone1($obj = null)
    {
        ?>
        <style>

            #save-one-data{
                display: none;
            }

        </style>

        <button data-code-pos="ppp1677328334565" id="print_profile" class="btn btn-info  m-2">
            <i class="fa fa-print"></i> &nbsp;
            IN HỒ SƠ
        </button>
        <button data-code-pos="ppp1677328334565" id="print_card" class="btn btn-default  m-2">
            <i class="fa fa-print"></i> &nbsp;
            IN THẺ
        </button>

        <button data-code-pos="ppp1677328334565" id="save-one-data2" class="btn btn-primary  m-2">
            <i class="fa fa-save"></i> &nbsp;
            GHI LẠI
        </button>

        <?php
    }

    public function commonJs()
    {
        ?>
        <script>

            function CallMultiCardA7(htmlx) {
                let WinPrint = window.open('', '', 'left=0,top=0,width=1024,height=800,toolbar=1,scrollbars=1,status=0');
                WinPrint.document.write('<html><head><title>In Danh sách Thẻ </title></head>');
                // WinPrint.document.write('<style>@page {size: A6 landscape;margin: 1%;}</style>');
                // WinPrint.document.write('<body style="font-family:verdana; font-size:14px;width:370px;height:270px:" >');
                WinPrint.document.write('<script src="/adminlte/plugins/jquery/jquery.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs@gh-pages/qrcode.min.js"></\script>');
                WinPrint.document.write('<link rel="stylesheet" href="/assert/css/print_multi_card_a7_in_a4.css?v=3">');
                WinPrint.document.write('<style type="text/css">  </style>');
                WinPrint.document.write('<body style="" >');
                WinPrint.document.write(htmlx);
                // WinPrint.document.write('<script src="/template/shop1/js/print_orders.js"></\script>');
                WinPrint.document.write('</body></html>');
                // WinPrint.document.close();
                WinPrint.focus();

            }

            function CallPrintA4(htmlx) {

                let WinPrint = window.open('', '', 'left=0,top=0,width=1024,height=800,toolbar=1,scrollbars=1,status=0');
                WinPrint.document.write('<html><head><title>In Hồ sơ Cá nhân</title></head>');
                // WinPrint.document.write('<style>@page {size: A6 landscape;margin: 1%;}</style>');
                // WinPrint.document.write('<body style="font-family:verdana; font-size:14px;width:370px;height:270px:" >');
                WinPrint.document.write('<script src="/adminlte/plugins/jquery/jquery.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs@gh-pages/qrcode.min.js"></\script>');
                WinPrint.document.write('<link rel="stylesheet" href="/assert/css/lad-common.css?v=1">');
                WinPrint.document.write('<link rel="stylesheet" href="/assert/css/print_page_a4.css?v=3">');
                WinPrint.document.write('<style type="text/css">  </style>');
                WinPrint.document.write('<body style="" >');
                WinPrint.document.write(htmlx);
                // WinPrint.document.write('<script src="/template/shop1/js/print_orders.js"></\script>');
                WinPrint.document.write('</body></html>');
                // WinPrint.document.close();
                WinPrint.focus();

                // WinPrint.close();
                // prtContent.innerHTML = "";
            }
        </script>
        <?php
    }

    public function extraJsIncludeEdit($objData = null)
    {

        $this->commonJs();
        ?>

        <script>

            $(document).on("click", "span.span_auto_complete", function () {
                $(this).parent().remove();
            });


            function CallPrintCard(htmlx) {

                let WinPrint = window.open('', '', 'left=0,top=0,width=800,height=600,toolbar=1,scrollbars=1,status=0');
                WinPrint.document.write('<html><head><title>In Thẻ Cá nhân</title></head>');
                // WinPrint.document.write('<style>@page {size: A6 landscape;margin: 1%;}</style>');
                // WinPrint.document.write('<body style="font-family:verdana; font-size:14px;width:370px;height:270px:" >');
                WinPrint.document.write('<script src="/adminlte/plugins/jquery/jquery.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></\script>');
                // WinPrint.document.write('<script src="https://cdn.jsdelivr.net/gh/davidshimjs/qrcodejs@gh-pages/qrcode.min.js"></\script>');
                WinPrint.document.write('<link rel="stylesheet" href="/assert/css/lad-common.css?v=1">');
                WinPrint.document.write('<link rel="stylesheet" href="/assert/css/print_ship.css">');
                WinPrint.document.write('<style type="text/css">  </style>');
                WinPrint.document.write('<body style="" >');
                WinPrint.document.write(htmlx);
                // WinPrint.document.write('<script src="/template/shop1/js/print_orders.js"></\script>');
                WinPrint.document.write('</body></html>');
                // WinPrint.document.close();
                WinPrint.focus();

                // WinPrint.close();
                // prtContent.innerHTML = "";
            }



            $(function (){

                $("#print_card").on('click', function (){
                    console.log(" Print profile ...");
                    let user_token = jctool.getCookie('_tglx863516839');
                    let ret = clsTableMngJs.saveOneDataTable(false)
                    if(!ret) {
                        alert("Error: Can not save?");
                    }
                    else{
                        console.log(" OK save");
                        let dataId = $('div[data-field-div="id"]').attr("data-id");
                        console.log("DataId = ", dataId);
                        let url = "/api/hr-employee/getHtmlPrintProfile?print_card=1";
                        $.ajax({
                            url: url,
                            type: 'POST',
                            beforeSend: function (xhr) {
                                xhr.setRequestHeader('Authorization', 'Bearer ' + user_token);
                            },
                            data: {datax: dataId},
                            success: function (data, status) {
                                console.log("Data ret: ", data, " \nStatus: ", status);
                                if(data.message && data.message == 'html_ready')
                                    if(data.payload){
                                        CallPrintCard(data.payload);
                                        console.log(" trigger save all Data ");

                                    }
                            },
                            error: function (data) {
                                console.log(" DATAx " , data);
                                if(data.responseJSON && data.responseJSON.message)
                                    alert('Error call api: ' + "\n" + data.responseJSON.message)
                                else
                                    alert('Error call api: ' + "\n" + url + "\n\n" + JSON.stringify(data).substr(0,1000));
                            }
                        });
                    }
                })

                $("#print_profile").on('click', function (){
                    console.log(" Print profile ...");
                    let user_token = jctool.getCookie('_tglx863516839');
                    let ret = clsTableMngJs.saveOneDataTable(false)
                    if(!ret) {
                        alert("Error: Can not save?");
                    }
                    else{
                        console.log(" OK save");
                        let dataId = $('div[data-field-div="id"]').attr("data-id");
                        console.log("DataId = ", dataId);
                        let url = "/api/hr-employee/getHtmlPrintProfile";
                        $.ajax({
                            url: url,
                            type: 'POST',
                            beforeSend: function (xhr) {
                                xhr.setRequestHeader('Authorization', 'Bearer ' + user_token);
                            },
                            data: {datax: dataId},
                            success: function (data, status) {
                                console.log("Data ret: ", data, " \nStatus: ", status);
                                if(data.message && data.message == 'html_ready')
                                    if(data.payload){
                                        CallPrintA4(data.payload);
                                        console.log(" trigger save all Data ");

                                    }
                            },
                            error: function (data) {
                                console.log(" DATAx " , data);
                                if(data.responseJSON && data.responseJSON.message)
                                    alert('Error call api: ' + "\n" + data.responseJSON.message)
                                else
                                    alert('Error call api: ' + "\n" + url + "\n\n" + JSON.stringify(data).substr(0,1000));
                            }
                        });
                    }
                })

            })

        </script>

        <script>

        $(function (){
            $("#save-one-data2").on('click', function (){

                let dataId = $("#form_save_one").data("id");

                console.log("...Save one 1");
                //Tự tạo userid nếu ko nhập:
                let uid = $("input.input_value_to_post[data-field='user_id']").val();

                let phone_number = $("input.input_value_to_post[data-field='phone_number']").val();

                if(phone_number[0] != '0'){
                    alert("Số điện thoại phải bắt đầu bằng số 0: " + phone_number);
                    return;
                }
                if(phone_number.length <10 || phone_number.length >11){
                    alert("Số điện thoại phải 10 đến 11 ký tự: " + phone_number);
                    return;
                }
                if(( "0" + parseInt(phone_number) + "").length <10 || ( "0" + parseInt(phone_number) + "").length >11){
                    alert("Số điện thoại phải 10 đến 11 ký tự (2) :  " + parseInt(phone_number));
                    return;
                }

                console.log("...UID/phone_number = ", uid , phone_number);

                if(uid){
                    clsTableMngJs.saveOneDataTable();
                }
                else{
                    if(!phone_number){
                        alert("Hãy nhập số điện thoại!");
                        return;
                    }
                    //Tạo user với phone number

                    console.log("Phone: ", phone_number);
                    //Tạo user với phone number:
                    let dataUser = {};
                    dataUser['username'] = phone_number;
                    dataUser['email'] = phone_number + "@" + '<?php echo getDomainHostName() ?>';
                    dataUser['password'] = '123hanoi';

                    let user_token = jctool.getCookie('_tglx863516839');
                    async function postJSON(data) {
                      try {
                        const response = await fetch("/api/user/add?return_if_exist=1", {
                          method: "POST", // or 'PUT'
                          headers: {
                            "Content-Type": "application/json",
                            'Authorization': 'Bearer ' + user_token,
                          },
                          body: JSON.stringify(data),
                        });

                        const result = await response.json();
                        if(response.status == 200){
                            console.log("Success:", result);
                            let uidAdded = result.payload;

                            let inputVal = $("input.input_value_to_post[data-field=user_id]")
                            inputVal.attr('value', uidAdded);
                            inputVal.prop('value', uidAdded);

                            $("<div><span title='Chọn user khác gắn vào thành viên này!' data-item-value='" + inputVal +"' data-autocomplete-id='" +
                            dataId + "-user_id' class='span_auto_complete'>  <b>" + phone_number + " </b> (" + uidAdded  + ") [X] </span></div>").insertBefore(inputVal);

                            clsTableMngJs.saveOneDataTable();

                            //Tạo thành công, lấy ra user id để đưa vào save User:
                            //alert(" OK ");

                        }else{
                            alert("Error: " + JSON.stringify(result));
                        }
                      } catch (error) {
                            console.error("Error:", error);
                            alert("Error: " + JSON.stringify(error))
                      }
                    }

                    postJSON(dataUser);


                }


            })
        })

        </script>

        <?php
    }

    public function extraJsInclude()
    {
        $this->commonJs();

        ?>

        <div class="create_login_acc" style="display: none; padding: 20px">
            <input type="text" data-lpignore="true" placeholder="Nhập username" style="margin-bottom: 10px; padding: 3px; width: 100%">

            <br>
            <input type="text" data-lpignore="true" placeholder="Nhập password" style="margin-bottom: 10px; padding: 3px; width: 100%">
            <br>
            <button type="button"> Tạo User </button>
        </div>

        <script>

            $(function (){



                $("#print_multi_card").on('click', function (){


                    let mIdPrint = clsTableMngJs.getSelectingCheckBox();

                    console.log(" Print profile ...", mIdPrint );

                    if(!mIdPrint.length){
                        alert("Hãy chọn nhân sự để in");
                        return;
                    }


                    let user_token = jctool.getCookie('_tglx863516839');
                    // let ret = clsTableMngJs.saveOneDataTable(false)
                    // if(!ret) {
                    //     alert("Error: Can not save?");
                    // }
                    // else{
                    //

                    if(1){
                        console.log(" OK save");

                        let url = "/api/hr-employee/getHtmlPrintProfile?print_multi_card=1";
                        $.ajax({
                            url: url,
                            type: 'POST',
                            beforeSend: function (xhr) {
                                xhr.setRequestHeader('Authorization', 'Bearer ' + user_token);
                            },
                            data: {all_id: mIdPrint},
                            success: function (data, status) {
                                console.log("Data ret: ", data, " \nStatus: ", status);
                                if(data.message && data.message == 'html_ready')
                                    if(data.payload){
                                        CallMultiCardA7(data.payload);
                                        console.log(" trigger save all Data ");

                                    }
                            },
                            error: function (data) {
                                console.log(" DATAx " , data);
                                if(data.responseJSON && data.responseJSON.message)
                                    alert('Error call api: ' + "\n" + data.responseJSON.message)
                                else
                                    alert('Error call api: ' + "\n" + url + "\n\n" + JSON.stringify(data).substr(0,1000));
                            }
                        });
                    }
                })



                $(".a_create_user_login").on('click', function (){
                    $( ".create_login_acc" ).dialog('open');
                })
            })

            $( ".create_login_acc" ).dialog({
                autoOpen: false,
                height: 300,
                width: 400,
                modal: true,
            });
        </script>


        <script>

            $("#show_report").on('click', function (){

                let mid = clsTableMngJs.getSelectingCheckBox();
                console.log(" MID ", mid);

                if(!mid || mid.length == 0){
                    alert("Cần chọn các thành viên muốn hiển thị bảng lương!");
                    return;
                }

                let strUid = '';
                for(let id of mid){
                    strUid += $("input[data-field=user_id][data-id="+id+"]").val() + ",";
                }
                console.log(" StrUID ", strUid);

                strUid = jctool.trimLeftRight(strUid , ',')

                let link = "/admin/hr-salary-month-user/report2?uid_list=" + strUid;
                window.open(link, "_blank");

            })

        </script>

<?php
    }

    //...
}
